import { translateTutorial as article, step as s, detail as d, question as q } from './translation';

const progress = s('Check download progress', 'Once the download starts, ClipDock shows Downloading, the progress percentage, and the downloaded size. Tap View Task or open Manager in the bottom navigation to follow the task. Wait for it to finish before opening the video.');
const save = s('Preview and save to Photos', 'Open the completed video in Manager and play it to check the picture and sound. If the preview contains several items, use the left and right arrows to select the right one. Tap Save to Photos, allow photo access if prompted, and check the result in Photos.');
const sourceTip = d('The link opens, but no media is found', 'Confirm that the video is still publicly accessible, then copy its share link again. Sign-in requirements, regional restrictions, and changes to the source page can affect extraction. Repeated retries may not resolve a source restriction.');
const photosQuestion = q('Why is a completed download missing from Photos?', 'The ClipDock library and the system Photos library are separate. Wait for the task to finish, then use Save to Photos and check photo permissions.');

export const platformTutorials = [
 article('download-tiktok-video-iphone', {
  title: 'How to download TikTok videos to Photos on iPhone in 2026',
  description: 'Copy a TikTok share link, extract the video in ClipDock, check its download, and save it to Photos. Includes four screenshots for iPhone and iPad.',
  intro: 'To keep a TikTok video you have the right to save, copy its share link and let ClipDock extract it. This guide covers a single video from link to Photos; iPad users can follow the same workflow.',
  steps: [s('Copy the video’s share link', 'Open the video in TikTok, open the share panel, and tap Copy link. Copy the link to this video, rather than the creator’s profile. The screenshots show the English interface.'), s('Submit the link to ClipDock', 'Open Extract in ClipDock, select Video, and check the link under Extract from Link. Fill from Clipboard is enabled in the screenshot, so the copied link is already filled in. If the field is empty, tap Paste. Check the link, then tap Extract.'), progress, s('Preview and save to Photos', 'In Manager, open the video from the Done list and tap Play to preview it. Once you have confirmed the content, tap Save to Photos. Allow saving if iOS asks for photo access, then check the result in Photos.')],
  tips: [sourceTip], faq: [photosQuestion, q('Can I save several TikTok videos in a row?', 'Use copy-to-download for links from different videos. For a collection from one creator, see the profile batch download guide. These workflows use different inputs.')],
 }),
 article('download-douyin-video-iphone', {
  title: 'How to download Douyin videos to Photos on iPhone in 2026',
  description: 'Use a Douyin share link to extract and download a video in ClipDock, then save it to Photos. Four reused TikTok screenshots illustrate the workflow.',
  intro: 'Copy the share link of a Douyin video you have the right to save, then use ClipDock to extract it. iPad users can follow the same steps. This guide reuses TikTok screenshots: the platform, links, and media shown are illustrations of the workflow, not a recorded Douyin test.',
  steps: [s('Copy the video’s share link', 'Open the video in Douyin, open its share panel, and choose Copy link. Use the individual video link, rather than a creator profile. The illustration shows TikTok’s Copy link option; the position of Douyin’s button depends on its current interface.'), s('Submit the Douyin link to ClipDock', 'Open Extract, select Video, and check the Extract from Link field. Fill from Clipboard is enabled in the illustration. For your own download, enter the Douyin video link you copied, or tap Paste if the field is empty. Confirm it, then tap Extract.'), progress, save],
  tips: [sourceTip], faq: [photosQuestion, q('Why does the screenshot show a TikTok link?', 'The TikTok images illustrate copying, extracting, downloading, and saving. Use your own Douyin video link; available media depends on the actual extraction result.')],
 }),
 article('download-facebook-video-iphone', {
  title: 'How to download Facebook videos and Reels on iPhone and iPad',
  description: 'Copy a Facebook video link, choose the quality and format in ClipDock, download it, and save to Photos. Includes five screenshots and format notes.',
  intro: 'Start with a video’s share link to save it on your iPhone or iPad. This guide uses a Facebook Reel to show copying, quality selection, downloading, and saving. The five screenshots show the English interface.',
  steps: [s('Copy the Facebook video link', 'Open the video or Reel in Facebook, open the share panel, and tap Copy link in the Share to row at the bottom. Copy the current item’s link for the next step.'), s('Paste the link and extract the video', 'Open Extract in ClipDock and tap Paste under Extract from Link. Confirm that the link points to the Facebook video, then tap Extract. The example URL contains facebook.com/reel/. Automation switches such as Fill from Clipboard are off; manual pasting is sufficient.'), s('Choose the quality and file format', 'In Select Quality, check the thumbnail, resolution, format, and estimated size. This example offers 1080p WEBM at about 9.6 MB, 720p MP4 at about 6.8 MB, and 360p MP4 at about 909 KB. Select an option and tap Download. Available options depend on the result.', [d('Compare quality and size together', 'Higher resolutions can retain more detail; smaller versions can reduce transfer time and storage use. The listed size is an estimate, rather than the final file size.'), d('Check MP4 versus WEBM', 'The 1080p option in this example is .webm; the 720p and 360p options are .mp4. Resolution and file format are separate choices. Check actual compatibility when saving or opening the file in another app.'), d('Set a default quality only if you want to', 'Set this quality as default and don’t ask again saves the preference. Leave it off, as shown, if you want to compare quality, format, and size for each download.')]), s('Follow the download', 'The Downloading view shows percentage, speed, estimated time remaining, and downloaded size. Tap View Task or open Manager and wait for completion. The screenshot shows 94.58%, so the download is still in progress.'), s('Preview the result and save to Photos', 'Open the video from Manager’s Done list. The example result is about 11 seconds long and 9.04 MB, with its Facebook source link. Play it to check the picture and sound, then tap Save to Photos and follow the system prompts. Check Photos afterward.', [d('Downloading and saving to Photos are separate steps', 'Done means the file has downloaded into the app. You still need Save to Photos to export it to the system library. The screenshot shows this action, rather than a successful-save message.')])],
  tips: [d('No downloadable result?', 'Check that you copied the current video’s link and that the source is still accessible. If it has been deleted or access is restricted, check the source before retrying.')],
  faq: [q('Does this example use Facebook Reels?', 'Yes. Its source URL contains facebook.com/reel/. For other Facebook videos, copy the specific item’s link and check the actual available resources.'), q('Can every video be downloaded in 1080p?', 'No. The 1080p, 720p, and 360p options belong to this example. Other videos can return different resolutions, formats, and sizes.'), photosQuestion],
 }),
 article('download-xiaohongshu-video-iphone', {
  title: 'How to download Xiaohongshu videos on iPhone and iPad',
  description: 'Copy a Xiaohongshu video post’s share link, download it with ClipDock, and save it to Photos. Includes four screenshots and notes on multiple results.',
  intro: 'Start with a Xiaohongshu video post’s share link, then extract and download it in ClipDock. Four screenshots show the sequence. Contact avatars and usernames in the share panel have been blurred. The app controls shown are in English; source content may appear in Chinese.',
  steps: [s('Copy the video post’s link', 'Open the video post in Xiaohongshu and open Share. Find Copy link at the bottom of Share to; it is the second option from the left in the screenshot’s bottom row. Copy the current post’s share content.'), s('Paste the share content and extract', 'Open Extract in ClipDock and tap Paste under Extract from Link. The example contains a Chinese caption about a car together with a Xiaohongshu short link. Check that the target link is included, then tap Extract.', [d('Share text can be pasted with the link', 'The example retains the share caption and proceeds to download. Make sure the pasted content includes the link, rather than just the title. If no link is detected, copy it again or try pasting only the URL.')]), s('Check download progress', 'The Downloading view shows percentage and downloaded size. This screenshot reads 60.03% and 2.44 MB / 4.06 MB, so the task is not finished. Tap View Task or open Manager and wait for it to complete.'), s('Check the media and save to Photos', 'Open the completed video in Manager and play it to check the picture and sound. The example is about 31 seconds and 4.06 MB, with its Xiaohongshu source link. Tap Save to Photos, follow the prompts, and check Photos.', [d('Switch between items with the arrows', 'The preview header shows 1 / 2: the first of two items. Tap the right arrow to inspect the next item before deciding what to save. The counter alone does not establish the other item’s contents or format. Resource counts vary by result.'), d('Save after downloading', 'Downloading into the app and saving to Photos are separate steps. If the video is missing from Photos, check that you tapped Save to Photos, then check permissions and the save message. The screenshot does not show a successful-save confirmation.')])],
  tips: [d('Nothing is extracted after pasting', 'Make sure the share content contains the complete link and the source post still opens. Check whether it has been deleted or its access restricted.')],
  faq: [q('Must I remove the share caption first?', 'The illustrated download succeeds with both the caption and short URL. If link detection fails, copy the link again or try retaining only the URL.'), q('Does every post return two items?', 'No. The 1 / 2 counter belongs to this result. Other posts may return different amounts and kinds of media.'), q('Does this guide also demonstrate image posts?', 'No. These screenshots show a video post, and do not establish the workflow for image posts.')],
 }),
 article('download-bilibili-video-iphone', {
  title: 'How to download Bilibili videos on iPhone and iPad',
  description: 'Copy a Bilibili video link, choose a quality in ClipDock, download it, and save it to Photos. Includes five screenshots of a single-video workflow.',
  intro: 'Copy a video’s share link in Bilibili and submit it to ClipDock. This example uses a video labeled as a background-music version and explains quality selection, progress, previewing, and saving. Bilibili’s source interface and video title in the screenshots are in Chinese.',
  steps: [s('Copy the Bilibili video link', 'Open the video in Bilibili and open its share panel. Tap Copy link, positioned to the right of Weibo in the screenshot. This is the specific video page’s link. To save multiple uploads from a creator, use the profile batch download guide.'), s('Paste the link and extract', 'Open Extract in ClipDock, select Video, and tap Paste under Extract from Link. Check the URL and tap Extract. This example uses the b23.tv short share link directly. Automatic filling and downloading can remain off for this manual workflow.'), s('Choose a quality and start downloading', 'Check the thumbnail and the background-music-version title in Select Quality. The selected option is 1080p MP4, estimated at 55.3 MB. The list also shows 720p MP4 at about 27.5 MB, 480p MP4 at about 17.8 MB, and a 360p option below. Tap Download.', [d('Balance resolution and size', 'Higher resolution may retain more detail and use more space. Compare the estimates for your needs. These values belong to this example; other videos can return different options.'), d('Decide whether to save a quality preference', 'Set this quality as default and don’t ask again stores the chosen quality. Leave it off to compare options each time.')]), s('Monitor the download', 'Downloading shows percentage, speed, time remaining, and downloaded size. This screenshot is at 15.00%, so you still need to wait. Tap View Task or open Manager to check the task.'), s('Preview and save the video', 'Open the completed video from Done in Manager. The result shows the background-music-version title, about 8 minutes 55 seconds, and 46.44 MB. Playback is at 00:56, and the source link is retained. Play the video to check it, then use Save to Photos.', [d('Use the final file information', 'The quality estimate, in-progress size, and final size can differ. The result here is 46.44 MB. Check the actual file and playback.'), d('1 / 63 is a position in the preview list', 'The header shows 1 / 63 and the Done list behind it contains 63 items. This does not mean the video has 63 parts. Confirm the title and source; the arrows switch between preview items.'), d('Done does not mean saved to Photos', 'After tapping Save to Photos, check permissions and the save message, then open Photos. The screenshot shows the save action, rather than a successful-save confirmation.')])],
  tips: [d('Check the video version', 'This example returns a background-music version. If the source has multiple versions or episodes, check the returned title, thumbnail, and downloaded contents before saving.')],
  faq: [q('Can I use a b23.tv short URL directly?', 'This example copies a b23.tv link from the video share panel and successfully downloads it. Make sure it points to the intended video.'), q('Does every video offer 1080p?', 'No. Use the resolutions returned for your link.'), q('Does this demonstrate downloading every part of a video?', 'No. The screenshots show extracting and downloading one video, and do not prove that all parts are included.'), q('How do I download more uploads from a creator?', 'Copy the creator’s profile link and load it in Batch. See the Bilibili profile batch download guide.')],
 }),
 article('download-youtube-video-iphone', {
  title: 'How to download YouTube videos on iPhone and iPad in 2026',
  description: 'Use ClipDock to extract a YouTube video link, choose a quality, follow the download, and save to Photos. Includes five screenshots.',
  intro: 'Start with the share link of the YouTube video you want to save. Download only content you own or have permission to use, and check the resources actually returned by ClipDock.',
  steps: [s('Copy the YouTube video link', 'Open the video in YouTube, tap Share, and choose Copy link. Use the specific video’s link, rather than a search result or channel page. The screenshots show the English interface.'), s('Paste the link into ClipDock', 'Open Extract, choose Video, and find Extract from Link. Paste the copied link, or confirm it if already filled in, then tap Extract.'), s('Choose a quality and download', 'Check the thumbnail and available options in Select Quality. The screenshot offers 1080p, 720p, and 480p among its options, with MP4 format and estimated sizes. Compare them, choose the resource you want, and tap Download. Available options depend on the video. The switch at the bottom can save a default quality.'), s('Check download progress', 'Downloading shows percentage, speed, estimated time remaining, and downloaded size. Tap View Task or open Manager and wait for completion.'), save],
  tips: [d('The downloaded file has no sound', 'Check which resource type you selected and try another video resource if one is available. Merge Audio and Video requires an audio input you already have; it cannot supply a missing track on its own.')],
  faq: [q('Can I download an entire channel with this workflow?', 'A channel is a batch extraction task, rather than a single-video download. Use the channel or list workflow and check the items actually returned.'), q('Will every video have a high-quality option?', 'No. Available resources depend on the source file, platform response, and access conditions. Check the extraction results.')],
 }),
 article('download-instagram-reels-iphone', {
  title: 'How to download Instagram Reels on iPhone in 2026',
  description: 'Save an Instagram Reel on iPhone or iPad with ClipDock: copy its link, extract and download the video, then save to Photos. Includes four screenshots.',
  intro: 'To save an Instagram Reel, obtain the share link to the Reel itself. This guide starts at Copy link and continues through extraction, downloading, and saving to Photos.',
  steps: [s('Copy the Reel’s share link', 'Open the Reel in Instagram, tap Share, and choose Copy link at the bottom of the share panel. Use the link to the Reel, rather than the creator’s profile. The screenshots use English controls.'), s('Submit the link and extract', 'Open Extract in ClipDock, choose Video, and find Extract from Link. The screenshot has the link filled from the clipboard. If the input is empty, tap Paste. Check that it is the intended Reel, then tap Extract.'), progress, save],
  tips: [d('Private accounts and unavailable posts', 'A link does not grant access permission. If a source requires a particular signed-in account, or a post or link has expired, this public-link workflow may not retrieve the media.')],
  faq: [q('Does this also demonstrate Instagram Stories?', 'This guide is for Reels. Stories have different links, expiry times, and access conditions. A successful Reel download is not evidence for Story support.'), q('How do I save several videos from one creator?', 'Use the creator’s profile link in the batch workflow. See the Instagram profile download guide.')],
 }),
 article('download-x-twitter-video-iphone', {
  title: 'How to download X (Twitter) videos on iPhone in 2026',
  description: 'Copy an X post link, choose a video quality in ClipDock, download it, and save it to Photos on iPhone or iPad. Includes five screenshots.',
  intro: 'Copy the link to the X post containing the video you want. A username, profile page, or screenshot of the post’s text cannot replace that URL.',
  steps: [s('Copy the post containing the video', 'Open the post in X, tap Share, and choose Copy Link at the bottom of the panel. The center of the screenshot is an X Chat setup prompt. The correct control is Copy Link at the lower left, rather than the central Set up button.'), s('Submit the post link', 'Open Extract in ClipDock, choose Video, and tap Paste under Extract from Link. If the link is already filled in, check it and tap Extract.'), s('Choose the quality and download', 'In Select Quality, check the thumbnail and choose a resolution. The example offers 720p, 480p, and 360p MP4 options with estimated sizes. Tap Download. Available qualities depend on the actual result. The bottom switch can save the quality as your default.'), s('Follow the download', 'Downloading shows percentage, speed, estimated time remaining, and downloaded size. Tap View Task or open Manager to check the task and wait for completion.'), save],
  tips: [d('The post contains media, but not the video you wanted', 'Check whether the link points to the original post, a quoted post, or a profile. Confirm the actual extracted media, rather than relying only on the post text.')],
  faq: [q('What if the account requires sign-in?', 'Access conditions may prevent retrieval. Copying a link does not bypass sign-in, private accounts, or other access controls.'), q('Can I extract the sound after downloading?', 'Use Extract Audio on a saved video that contains an audio track. The available output format depends on the tool’s actual options.')],
 }),
];
