import type { HomeFeatures, HomeTools } from '../home/types';
import { platformNotes } from './tutorial-index';

export const capabilities = ['Liens de partage', 'Téléchargement par URL', 'Copier pour télécharger', 'Sans changer d’application', 'Détection de vidéos web', 'Profils par lot', 'Chaînes par lot', 'Hashtags par lot', 'Playlists par lot', 'Collections par lot', 'Téléchargement en arrière-plan', 'Gestion des vidéos', 'Enregistrement dans Photos', 'Découpage', 'Conversion', 'Assemblage', 'Redimensionnement', 'Rotation', 'Miroir', 'Vitesse', 'Extraction audio', 'Fusion audio et vidéo', 'Lecture inversée', 'Filigranes', 'Création de GIF', 'Création de Live Photos', 'Capture d’images', 'Modification du MD5', 'Sous-titres YouTube'];

export const featureSections: HomeFeatures = [
  { number: '01', video: 'share-link', kicker: 'Du lien à la vidéo', title: 'Collez un lien.\nGardez la vidéo.', description: 'Collez un lien de partage compatible ou une adresse web pour extraire les vidéos, images ou fichiers audio disponibles. Choisissez une version HD ou sans filigrane si la source en propose une. La qualité, le format et la présence d’un filigrane dépendent du média source.', points: ['Voir les plateformes compatibles', 'Choisir parmi les qualités disponibles', 'Télécharger vidéos, images et audio', 'Poursuivre les téléchargements en arrière-plan'], platformDetails: platformNotes.platform, placeholder: 'Aperçu de l’extraction par lien', tone: 'blue' },
  { number: '02', video: 'copy-background', kicker: 'Il suffit de copier', title: 'Continuez à regarder.\nClipDock télécharge.', description: 'Activez « Liens de téléchargement automatique » et « Détecter en arrière-plan », puis gardez l’image dans l’image active. Copiez un lien compatible depuis YouTube, TikTok, X ou une autre plateforme pour créer un téléchargement en arrière-plan. Activez les notifications de téléchargement et autorisez-les dans le système pour recevoir les alertes de fin ou d’échec.', points: ['Plus besoin de revenir coller chaque lien', 'Rangez la fenêtre flottante au bord de l’écran'], placeholder: 'Aperçu des tâches de téléchargement', tone: 'lime' },
  { number: '03', video: 'web-long-press', kicker: 'Détectez la vidéo en cours de lecture', title: 'Lisez la vidéo.\nMaintenez pour choisir.', description: 'Ouvrez une page dans « Vidéo web » et lancez la vidéo. Passez les publicités ou attendez leur fin, puis maintenez le doigt sur la vidéo pour choisir un média téléchargeable. Le détecteur en bas affiche aussi les vidéos repérées. Leur disponibilité dépend du site et des conditions d’accès.', points: ['Détecter les vidéos disponibles sur la page', 'Choisir un média dans la liste', 'Repérer la vidéo par un appui long'], placeholder: 'Aperçu du navigateur intégré', tone: 'coral' },
  { number: '04', video: 'batch-playlist', kicker: 'Téléchargement par lot', title: 'Une sélection.\nUne file de téléchargement.', description: 'Collez un lien de chaîne, de profil, de playlist ou de hashtag compatible. Chargez la liste, sélectionnez les vidéos ou images souhaitées, puis ajoutez-les à la file. Les listes se chargent page par page ; la version gratuite se limite aux 2 premières pages. Les résultats disponibles ne comprennent pas nécessairement toutes les publications.', points: ['Voir les sources compatibles par lot'], platformDetails: platformNotes.batch, placeholder: 'Aperçu du téléchargement de listes', tone: 'blue' },
  { number: '05', kicker: 'Sous-titres YouTube', title: 'Gardez aussi\nles sous-titres.', description: 'Collez un lien de vidéo YouTube pour extraire ses sous-titres existants. Choisissez les langues et le format, puis enregistrez les fichiers ou partagez-les avec une autre application pour les lire, les classer ou les réutiliser.', points: ['Sous-titres automatiques et langues déjà disponibles', 'Sélection multiple et sept formats, dont SRT et VTT', 'Enregistrer dans Fichiers ou partager directement'], carousel: true, tutorial: 'extract-youtube-subtitles-iphone', tone: 'lime' }
];

export const tools: HomeTools = [
  { mark: 'CUT', slug: 'trim-video-iphone', title: 'Couper une vidéo', description: 'Gardez le passage qui vous intéresse.' },
  { mark: 'CONV', slug: 'transcode-video-iphone', title: 'Convertir une vidéo', description: 'Changez le format de votre vidéo selon vos besoins.' },
  { mark: 'JOIN', slug: 'join-videos-iphone', title: 'Assembler des vidéos', description: 'Réunissez plusieurs clips dans l’ordre de votre choix.' },
  { mark: 'MIX', slug: 'interleave-videos-iphone', title: 'Alterner des clips', description: 'Découpez plusieurs vidéos et alternez leurs segments.' },
  { mark: 'GRID', slug: 'segment-grid-video-iphone', title: 'Créer une grille vidéo', description: 'Affichez plusieurs passages d’une vidéo dans une grille.' },
  { mark: 'SIZE', slug: 'resize-video-iphone', title: 'Adapter le cadre', description: 'Changez le format du cadre et choisissez les marges, le recadrage ou une autre disposition.' },
  { mark: 'ROTATE', slug: 'rotate-video-iphone', title: 'Faire pivoter une vidéo', description: 'Tournez l’image dans le sens voulu.' },
  { mark: 'MIRROR', slug: 'mirror-video-iphone', title: 'Créer un effet miroir', description: 'Retournez l’image pour obtenir un reflet.' },
  { mark: 'SPEED', slug: 'change-video-speed-iphone', title: 'Modifier la vitesse', description: 'Accélérez ou ralentissez le rythme de votre vidéo.' },
  { mark: 'AUDIO', slug: 'extract-audio-iphone', title: 'Extraire l’audio', description: 'Enregistrez le son d’une vidéo dans un fichier audio.' },
  { mark: 'SOUND', slug: 'edit-video-audio-iphone', title: 'Modifier le son', description: 'Coupez le son d’une vidéo ou réglez son volume.' },
  { mark: 'MERGE', slug: 'merge-audio-video-iphone', title: 'Fusionner audio et vidéo', description: 'Réunissez une piste audio et une vidéo dans un seul fichier.' },
  { mark: 'REVERSE', slug: 'reverse-video-iphone', title: 'Inverser une vidéo', description: 'Faites défiler votre vidéo de la fin vers le début.' },
  { mark: 'MARK', slug: 'add-watermark-video-iphone', title: 'Ajouter un filigrane', description: 'Ajoutez du texte ou une image à vos propres vidéos.' },
  { mark: 'GIF', slug: 'video-to-gif-iphone', title: 'Créer un GIF', description: 'Transformez un extrait vidéo en animation à partager.' },
  { mark: 'LIVE', slug: 'video-to-live-photo-iphone', title: 'Créer une Live Photo', description: 'Transformez un extrait vidéo en Live Photo.' },
  { mark: 'FRAMES', slug: 'capture-video-frames-iphone', title: 'Capturer des images', description: 'Extrayez une image, une série de captures, une sélection intelligente ou une planche d’aperçu. Les modes avancés nécessitent VIP.' },
  { mark: 'MD5', slug: 'change-video-md5-iphone', title: 'Modifier le MD5', description: 'Modifiez l’empreinte MD5 d’un fichier vidéo.' }
];

export const faqs = [
  { question: 'Quels liens ClipDock prend-il en charge ?', answer: platformNotes.platform },
  { question: 'Pourquoi certains liens ne fonctionnent-ils pas ?', answer: 'Une modification de page, une connexion requise, des restrictions régionales, le réseau, un média expiré, les DRM ou les contrôles d’accès peuvent empêcher l’extraction. Vérifiez que le lien s’ouvre normalement, puis réessayez.' },
  { question: 'Où sont enregistrées les vidéos téléchargées ?', answer: 'Dans « Gestion », la liste « Terminé » permet de prévisualiser, rechercher, trier et partager vos vidéos. Touchez « Enregistrer dans Photos » pour les enregistrer manuellement, ou activez « Enregistrement automatique des téléchargements terminés dans Photos » dans « Paramètres de téléchargement ». L’enregistrement nécessite l’autorisation Photos et un format compatible.' },
  { question: 'Les téléchargements continuent-ils en arrière-plan ?', answer: 'ClipDock prend en charge le téléchargement en arrière-plan. iOS peut toutefois ajuster le temps d’activité selon les ressources système, le réseau et les réglages d’économie d’énergie.' },
  { question: 'ClipDock collecte-t-il mes données ?', answer: 'La fiche de confidentialité actuelle de l’App Store indique qu’aucune donnée n’est collectée par le développeur via cette application. Les sites et ressources tiers peuvent traiter les informations habituelles des requêtes réseau selon leur propre politique de confidentialité.' },
  { question: 'Puis-je télécharger n’importe quelle vidéo en ligne ?', answer: 'Enregistrez uniquement les contenus dont vous détenez les droits, que vous êtes autorisé à utiliser ou que la loi vous permet d’enregistrer. Respectez les règles du propriétaire, du site et de votre région.' }
];

export const ui = {
  ogAlt: 'ClipDock — Téléchargez des vidéos web sur iPhone et iPad', eyebrow: 'De nombreuses plateformes · iPhone + iPad', heroLine1: 'Un lien à copier.', heroLine2: 'Une vidéo à garder.',
  heroDescription: 'Enregistrez les vidéos, images et fichiers audio de liens de partage et de pages web compatibles. Lancez les téléchargements en copiant des liens ou sélectionnez plusieurs publications dans une liste. La qualité, le format et les filigranes dépendent de la source.',
  freeDownload: 'Télécharger gratuitement', qrLabel: 'Scannez avec votre iPhone pour télécharger ClipDock', qrAlt: 'Code QR pour télécharger ClipDock', scan: 'Scannez avec votre iPhone', getApp: 'Télécharger', productInfo: 'Informations sur l’application', ratings: 'avis', privacyProof: 'Aucune donnée collectée par l’app', capabilities: 'Fonctionnalités de ClipDock', subtitleLink: 'Lire le tutoriel sur les sous-titres', demoSuffix: ' — démonstration', progress: 'Progression de la lecture', placeholder: 'Image à venir',
  toolsKicker: 'Après le téléchargement', toolsTitle: 'Vos outils vidéo, partout.', toolsDescription: 'Enregistrer n’est que le début. Coupez, convertissez, assemblez et partagez vos vidéos avec les outils intégrés à ClipDock.', readTutorial: 'Lire le tutoriel',
  trustKicker: 'Des possibilités bien définies', trustTitle: 'Des outils utiles. Des limites claires.', trustDescription: 'ClipDock s’adresse aux contenus que vous avez le droit d’enregistrer et de modifier. La disponibilité dépend de la plateforme et du média source.', trustValue1: 'Aucune collecte', trustLabel1: 'Données de l’application', trustText1: 'La fiche de confidentialité actuelle de l’App Store indique que le développeur ne collecte pas de données via cette application.', trustLabel2: 'iPhone et iPad', trustText2: 'Compatible avec iOS 15 et iPadOS 15, ou une version ultérieure.', trustValue3: 'Vos droits', trustLabel3: 'Enregistrez les contenus autorisés', trustText3: 'Aucun contournement des DRM, des accès payants, des contrôles d’accès ou des restrictions des plateformes.',
  faqKicker: 'Questions fréquentes', faqTitle: 'Avant de télécharger.', closingKicker: 'Un nouveau lien à enregistrer ?', closingTitle: 'Gardez vos vidéos à portée de main.', closingDescription: 'ClipDock est disponible gratuitement sur iPhone et iPad, avec achats intégrés.', storeDownload: 'Télécharger sur l’App Store', closingQr: 'Scannez pour télécharger ClipDock'
};
