import { videoToolScreenshots, videoToolTutorials, videoToolOrder } from "./video-tools";

export const categories = [
	{ id: "platform", name: "按平台下载", description: "从分享链接开始，把需要的视频保存到设备。" },
	{ id: "clipboard", name: "复制即下载", description: "减少切换 App，让复制链接接上下载任务。" },
	{ id: "batch", name: "批量下载", description: "按频道、主页或播放列表集中保存视频。" },
	{ id: "subtitles", name: "字幕提取", description: "提取 YouTube 已有字幕，选择语言与格式后保存或分享。" },
	{ id: "tools", name: "视频处理", description: "18 个视频处理功能：从裁剪、转码到声音、画布与组合效果。" },
] as const;

// Set src only after the corresponding real screenshot has been supplied.
export const screenshotBriefs: Record<string, { title: string; brief: string; src?: string; width?: number; height?: number; framed?: boolean; video?: string; poster?: string; highlight?: { x: number; y: number; width: number; height: number } }> = {
	"bilibili-copy-link-orange": { title: "在 B 站视频分享面板点击复制链接", brief: "用户提供的 Bilibili 单视频下载截图，橙色手机壳。", src: "/assets/tutorials/bilibili/copy-link-orange.webp", width: 1319, height: 2748, framed: true },
	"bilibili-extract-link-orange": { title: "在 Video 分页粘贴短链接并点击 Extract", brief: "用户提供的 Bilibili 单视频下载截图，橙色手机壳。", src: "/assets/tutorials/bilibili/extract-link-orange.webp", width: 1319, height: 2748, framed: true },
	"bilibili-select-quality-orange": { title: "选择清晰度，核对预计大小后点击 Download", brief: "用户提供的 Bilibili 单视频下载截图，橙色手机壳。", src: "/assets/tutorials/bilibili/select-quality-orange.webp", width: 1319, height: 2748, framed: true },
	"bilibili-download-progress-orange": { title: "查看下载进度并打开对应任务", brief: "用户提供的 Bilibili 单视频下载截图，橙色手机壳。", src: "/assets/tutorials/bilibili/download-progress-orange.webp", width: 1319, height: 2748, framed: true },
	"bilibili-save-photos-orange": { title: "预览下载的视频，再保存到相册", brief: "用户提供的 Bilibili 单视频下载截图，橙色手机壳。", src: "/assets/tutorials/bilibili/save-photos-orange.webp", width: 1319, height: 2748, framed: true },
	"bilibili-batch-profile-orange": { title: "在 B 站 UP 主主页分享面板点击复制链接", brief: "用户提供的 Bilibili 主页批量下载截图，橙色手机壳。", src: "/assets/tutorials/bilibili-batch/profile-orange.webp", width: 1319, height: 2748, framed: true },
	"bilibili-batch-input-orange": { title: "在 Batch 分页粘贴 B 站主页分享短链接", brief: "用户提供的 Bilibili 主页批量下载截图，橙色手机壳。", src: "/assets/tutorials/bilibili-batch/input-orange.webp", width: 1319, height: 2748, framed: true },
	"bilibili-batch-loading-orange": { title: "点击 Load list，等待作品列表加载", brief: "用户提供的 Bilibili 主页批量下载截图，橙色手机壳。", src: "/assets/tutorials/bilibili-batch/loading-orange.webp", width: 1319, height: 2748, framed: true },
	"bilibili-batch-select-orange": { title: "选择视频、加载下一页并设置批量画质", brief: "用户提供的 Bilibili 主页批量下载截图，橙色手机壳。", src: "/assets/tutorials/bilibili-batch/select-orange.webp", width: 1319, height: 2748, framed: true },
	"bilibili-batch-queue-orange": { title: "在 Manager 查看 B 站视频下载队列", brief: "用户提供的 Bilibili 主页批量下载截图，橙色手机壳。", src: "/assets/tutorials/bilibili-batch/queue-orange.webp", width: 1319, height: 2748, framed: true },
	"weibo-batch-profile-orange": { title: "在微博主页分享面板复制主页链接", brief: "用户提供的微博主页批量下载截图，橙色手机壳。", src: "/assets/tutorials/weibo-batch/profile-orange.webp", width: 1319, height: 2748, framed: true },
	"weibo-batch-input-orange": { title: "在 Batch 分页粘贴微博主页地址", brief: "用户提供的微博主页批量下载截图，橙色手机壳。", src: "/assets/tutorials/weibo-batch/input-orange.webp", width: 1319, height: 2748, framed: true },
	"weibo-batch-loading-orange": { title: "点击 Load list，等待列表加载", brief: "用户提供的微博主页批量下载截图，橙色手机壳。", src: "/assets/tutorials/weibo-batch/loading-orange.webp", width: 1319, height: 2748, framed: true },
	"weibo-batch-select-orange": { title: "选择资源，按需加载下一页并加入队列", brief: "用户提供的微博主页批量下载截图，橙色手机壳。", src: "/assets/tutorials/weibo-batch/select-orange.webp", width: 1319, height: 2748, framed: true },
	"weibo-batch-queue-orange": { title: "在 Manager 查看微博视频的下载进度", brief: "用户提供的微博主页批量下载截图，橙色手机壳。", src: "/assets/tutorials/weibo-batch/queue-orange.webp", width: 1319, height: 2748, framed: true },
	"tiktok-batch-profile-orange": { title: "在 TikTok 主页分享面板点击 Copy link", brief: "用户提供的 TikTok 批量下载截图；抖音篇复用作流程示意。", src: "/assets/tutorials/tiktok-batch/profile-orange.webp", width: 1319, height: 2748, framed: true },
	"tiktok-batch-input-orange": { title: "在 Batch 分页粘贴作者主页链接", brief: "用户提供的 TikTok 批量下载截图；抖音篇复用作流程示意。", src: "/assets/tutorials/tiktok-batch/input-orange.webp", width: 1319, height: 2748, framed: true },
	"tiktok-batch-loading-orange": { title: "等待 Loading list 完成", brief: "用户提供的 TikTok 批量下载截图；抖音篇复用作流程示意。", src: "/assets/tutorials/tiktok-batch/loading-orange.webp", width: 1319, height: 2748, framed: true },
	"tiktok-batch-select-orange": { title: "筛选资源、确认画质并加入队列", brief: "用户提供的 TikTok 批量下载截图；抖音篇复用作流程示意。", src: "/assets/tutorials/tiktok-batch/select-orange.webp", width: 1319, height: 2748, framed: true },
	"tiktok-batch-queue-orange": { title: "在 Manager 查看排队、下载与失败状态", brief: "用户提供的 TikTok 批量下载截图；抖音篇复用作流程示意。", src: "/assets/tutorials/tiktok-batch/queue-orange.webp", width: 1319, height: 2748, framed: true },
	"instagram-batch-profile-orange": { title: "在 Instagram 主页菜单点击 Copy profile URL", brief: "用户提供的 Instagram 主页批量下载截图，橙色手机壳。", src: "/assets/tutorials/instagram-batch/profile-orange.webp", width: 1319, height: 2748, framed: true },
	"instagram-batch-input-orange": { title: "切换 Batch，粘贴 Instagram 主页链接", brief: "用户提供的 Instagram 主页批量下载截图，橙色手机壳。", src: "/assets/tutorials/instagram-batch/input-orange.webp", width: 1319, height: 2748, framed: true },
	"instagram-batch-loading-orange": { title: "点击 Load list，等待列表加载", brief: "用户提供的 Instagram 主页批量下载截图，橙色手机壳。", src: "/assets/tutorials/instagram-batch/loading-orange.webp", width: 1319, height: 2748, framed: true },
	"instagram-batch-select-orange": { title: "筛选媒体、选择条目并设置批量画质", brief: "用户提供的 Instagram 主页批量下载截图，橙色手机壳。", src: "/assets/tutorials/instagram-batch/select-orange.webp", width: 1319, height: 2748, framed: true },
	"instagram-batch-queue-orange": { title: "在 Manager 查看排队与下载进度", brief: "用户提供的 Instagram 主页批量下载截图，橙色手机壳。", src: "/assets/tutorials/instagram-batch/queue-orange.webp", width: 1319, height: 2748, framed: true },
	"xiaohongshu-copy-link": { title: "在小红书分享面板点击 Copy link（复制链接）", brief: "用户提供的小红书操作截图，橙色手机壳；分享面板头像和用户名已模糊。", src: "/assets/tutorials/xiaohongshu/copy-link-orange.webp", width: 1319, height: 2748, framed: true },
	"xiaohongshu-extract-link": { title: "粘贴带链接的分享文案，点击 Extract（提取）", brief: "用户提供的小红书操作截图，橙色手机壳。", src: "/assets/tutorials/xiaohongshu/extract-link-orange.webp", width: 1319, height: 2748, framed: true },
	"xiaohongshu-download-progress": { title: "等待下载完成，点击 View Task（查看任务）", brief: "用户提供的小红书操作截图，橙色手机壳。", src: "/assets/tutorials/xiaohongshu/download-progress-orange.webp", width: 1319, height: 2748, framed: true },
	"xiaohongshu-save-photos": { title: "切换并预览资源，点击 Save to Photos（保存到相册）", brief: "用户提供的小红书操作截图，橙色手机壳。", src: "/assets/tutorials/xiaohongshu/save-photos-orange.webp", width: 1319, height: 2748, framed: true },
	"facebook-copy-link": { title: "在 Facebook 分享面板底部点击 Copy link（复制链接）", brief: "用户提供的 IMG_8169.PNG，橙色手机壳。", src: "/assets/tutorials/facebook/copy-link-orange.webp", width: 1319, height: 2748, framed: true },
	"facebook-extract-link": { title: "粘贴 Facebook Reels 链接，点击 Extract（提取）", brief: "用户提供的 IMG_3446.PNG，橙色手机壳。", src: "/assets/tutorials/facebook/extract-link-orange.webp", width: 1319, height: 2748, framed: true },
	"facebook-select-quality": { title: "核对清晰度、格式与预计大小，点击 Download（下载）", brief: "用户提供的 IMG_3447.PNG，橙色手机壳。", src: "/assets/tutorials/facebook/select-quality-orange.webp", width: 1319, height: 2748, framed: true },
	"facebook-download-progress": { title: "查看下载进度，点击 View Task（查看任务）", brief: "用户提供的 IMG_3449.PNG，橙色手机壳。", src: "/assets/tutorials/facebook/download-progress-orange.webp", width: 1319, height: 2748, framed: true },
	"facebook-save-photos": { title: "预览已完成的视频，点击 Save to Photos（保存到相册）", brief: "用户提供的 IMG_3450.PNG，橙色手机壳。", src: "/assets/tutorials/facebook/save-photos-orange.webp", width: 1319, height: 2748, framed: true },
	...videoToolScreenshots,
	"subtitles-paste-link": { title: "在 Subtitles 分页粘贴 YouTube 视频链接", brief: "用户提供的 IMG_8163.PNG。", src: "/assets/tutorials/youtube-subtitles/paste-link.webp", width: 1320, height: 2868 },
	"subtitles-extracting": { title: "点击 Extract，等待字幕提取完成", brief: "用户提供的 IMG_8164.PNG。", src: "/assets/tutorials/youtube-subtitles/extracting.webp", width: 1320, height: 2868 },
	"subtitles-select-tracks": { title: "勾选需要导出的字幕语言轨道", brief: "用户提供的 IMG_8165.PNG。", src: "/assets/tutorials/youtube-subtitles/select-tracks.webp", width: 1320, height: 2868 },
	"subtitles-select-format": { title: "点击 Format，选择字幕文件格式", brief: "用户提供的 IMG_8166.PNG。", src: "/assets/tutorials/youtube-subtitles/select-format.webp", width: 1320, height: 2868 },
	"subtitles-export": { title: "点击 Export captions，保存到文件或分享", brief: "用户提供的 IMG_8167.PNG。", src: "/assets/tutorials/youtube-subtitles/export.webp", width: 1320, height: 2868 },

	"playlist-input-orange": { title: "在 Batch 分页填入 YouTube 播放列表链接", brief: "IMG_3435.PNG，橙色手机壳。", src: "/assets/tutorials/youtube-playlist/input-orange.webp", width: 1319, height: 2748, framed: true },
	"playlist-loading-orange": { title: "点击 Load list，等待列表加载", brief: "IMG_3436.PNG，橙色手机壳。", src: "/assets/tutorials/youtube-playlist/loading-orange.webp", width: 1319, height: 2748, framed: true },
	"playlist-select-orange": { title: "选择条目与批量画质，点击 Add to queue", brief: "IMG_3437.PNG，橙色手机壳。", src: "/assets/tutorials/youtube-playlist/select-orange.webp", width: 1319, height: 2748, framed: true },
	"playlist-queue-orange": { title: "在 Manager 查看排队与下载进度", brief: "IMG_3438.PNG，橙色手机壳。", src: "/assets/tutorials/youtube-playlist/queue-orange.webp", width: 1319, height: 2748, framed: true },
	"clipboard-enable-orange": { title: "开启剪贴板填入、自动下载与后台检测", brief: "IMG_3429.PNG，橙色手机壳。", src: "/assets/tutorials/clipboard/enable-orange.webp", width: 1319, height: 2748, framed: true },
	"clipboard-pip-orange": { title: "切回 TikTok，保持画中画悬浮窗开启", brief: "IMG_3430.PNG，橙色手机壳。", src: "/assets/tutorials/clipboard/pip-orange.webp", width: 1319, height: 2748, framed: true },
	"clipboard-copy-orange": { title: "在分享面板点击 Copy link（复制链接）", brief: "IMG_3431.PNG，橙色手机壳。", src: "/assets/tutorials/clipboard/copy-link-orange.webp", width: 1319, height: 2748, framed: true },
	"clipboard-demo": { title: "演示：连续复制链接，后台识别并创建下载任务", brief: "复制即后台下载录屏。", video: "/assets/demos/copy-background.mp4", poster: "/assets/demos/copy-background.jpg" },
	"x-copy-orange": { title: "在 X 分享面板底部点击 Copy Link（复制链接）", brief: "IMG_8145.PNG，橙色手机壳。", src: "/assets/tutorials/x/copy-link-orange.webp", width: 1319, height: 2748, framed: true },
	"x-extract-orange": { title: "确认帖子链接，点击 Extract（提取）", brief: "IMG_3424.PNG，橙色手机壳。", src: "/assets/tutorials/x/extract-link-orange.webp", width: 1319, height: 2748, framed: true },
	"x-quality-orange": { title: "选择清晰度，点击 Download（下载）", brief: "IMG_3425.PNG，橙色手机壳。", src: "/assets/tutorials/x/select-quality-orange.webp", width: 1319, height: 2748, framed: true },
	"x-progress-orange": { title: "查看下载进度，点击 View Task（查看任务）", brief: "IMG_3427.PNG，橙色手机壳。", src: "/assets/tutorials/x/download-progress-orange.webp", width: 1319, height: 2748, framed: true },
	"x-photos-orange": { title: "预览视频，点击 Save to Photos（保存到相册）", brief: "IMG_3428.PNG，橙色手机壳。", src: "/assets/tutorials/x/save-photos-orange.webp", width: 1319, height: 2748, framed: true },
	"instagram-copy-orange": { title: "在 Instagram 分享面板点击 Copy link（复制链接）", brief: "IMG_8141.PNG，橙色手机壳。", src: "/assets/tutorials/instagram/copy-link-orange.webp", width: 1319, height: 2748, framed: true },
	"instagram-extract-orange": { title: "确认 Reels 链接，点击 Extract（提取）", brief: "IMG_3417.PNG，橙色手机壳。", src: "/assets/tutorials/instagram/extract-link-orange.webp", width: 1319, height: 2748, framed: true },
	"instagram-progress-orange": { title: "查看下载进度，点击 View Task（查看任务）", brief: "IMG_3419.PNG，橙色手机壳。", src: "/assets/tutorials/instagram/download-progress-orange.webp", width: 1319, height: 2748, framed: true },
	"instagram-photos-orange": { title: "预览视频，点击 Save to Photos（保存到相册）", brief: "IMG_3420.PNG，橙色手机壳。", src: "/assets/tutorials/instagram/save-photos-orange.webp", width: 1319, height: 2748, framed: true },
	"youtube-copy-orange": { title: "在 YouTube 分享面板点击 Copy link（复制链接）", brief: "IMG_8140.PNG，橙色手机壳。", src: "/assets/tutorials/youtube/copy-link-orange.webp", width: 1319, height: 2748, framed: true },
	"youtube-extract-orange": { title: "填入 YouTube 链接，点击 Extract（提取）", brief: "IMG_3411.PNG，橙色手机壳。", src: "/assets/tutorials/youtube/extract-link-orange.webp", width: 1319, height: 2748, framed: true },
	"youtube-quality-orange": { title: "在 Select Quality 中选择清晰度，点击 Download", brief: "IMG_3412.PNG，橙色手机壳。", src: "/assets/tutorials/youtube/select-quality-orange.webp", width: 1319, height: 2748, framed: true },
	"youtube-progress-orange": { title: "查看下载进度、速度及预计剩余时间", brief: "IMG_3413.PNG，橙色手机壳。", src: "/assets/tutorials/youtube/download-progress-orange.webp", width: 1319, height: 2748, framed: true },
	"youtube-photos-orange": { title: "预览已下载的视频，点击 Save to Photos（保存到相册）", brief: "IMG_3414.PNG，橙色手机壳。", src: "/assets/tutorials/youtube/save-photos-orange.webp", width: 1319, height: 2748, framed: true },
	"tiktok-copy-orange": { title: "在 TikTok 分享面板中点击 Copy link（复制链接）", brief: "IMG_3407.PNG，橙色手机壳。", src: "/assets/tutorials/tiktok/copy-link-orange.webp", width: 1319, height: 2748, framed: true },
	"tiktok-extract-orange": { title: "确认分享链接后，点击 Extract（提取）", brief: "IMG_3408.PNG，橙色手机壳。", src: "/assets/tutorials/tiktok/extract-link-orange.webp", width: 1319, height: 2748, framed: true },
	"tiktok-progress-orange": { title: "查看下载进度，点击 View Task（查看任务）", brief: "IMG_3409.PNG，橙色手机壳。", src: "/assets/tutorials/tiktok/download-progress-orange.webp", width: 1319, height: 2748, framed: true },
	"tiktok-photos-orange": { title: "预览视频，点击 Save to Photos（保存到相册）", brief: "IMG_3410.PNG，橙色手机壳。", src: "/assets/tutorials/tiktok/save-photos-orange.webp", width: 1319, height: 2748, framed: true },
	"tiktok-link": { title: "复制 TikTok 分享链接", brief: "展示一条可公开访问、已获授权的视频及分享面板中的复制链接入口。" },
	"youtube-link": { title: "复制 YouTube 视频链接", brief: "展示普通视频的分享面板和复制链接入口，保留足够的平台上下文。" },
	"instagram-link": { title: "复制 Instagram Reels 链接", brief: "展示公开 Reels 的分享或更多菜单，以及实际的复制链接入口。" },
	"x-link": { title: "复制 X 帖子链接", brief: "展示含视频的公开帖子及复制帖子链接的实际入口。" },
	"link-input": { title: "在 ClipDock影随存中提交链接", brief: "展示 App 的链接输入页面和真实操作入口；示例链接不含登录令牌。" },
	"tiktok-result": { title: "TikTok 视频识别结果", brief: "展示该示例链接实际返回的资源、可用清晰度及下载入口，不伪造无水印或清晰度标签。" },
	"youtube-result": { title: "YouTube 视频识别结果", brief: "展示实际可选的资源、格式或清晰度，以及下载入口。" },
	"instagram-result": { title: "Reels 识别结果", brief: "展示与前一张 Reels 示例对应的视频资源和下载入口。" },
	"x-result": { title: "X 视频识别结果", brief: "展示与示例帖子对应的视频资源及下载入口。" },
	"library": { title: "已完成的视频与资料库", brief: "展示下载完成状态、预览或管理入口；隐藏无关个人文件。" },
	"save-photos": { title: "保存到系统相册", brief: "展示 App 中实际的保存到相册入口，可另附必要的照片权限提示。" },
	"clipboard-setting": { title: "复制即下载的开启方式", brief: "展示开启此功能的完整路径或设置页，保留开关说明、系统要求和前置条件。若无独立开关，请提供真实启动方式。" },
	"clipboard-task": { title: "复制后自动出现的下载任务", brief: "在复制示例链接后展示新增任务；最好补充录屏，证明中间没有回 App 粘贴。" },
	"download-notification": { title: "下载完成通知", brief: "展示 App 的真实完成通知，隐藏其他通知及个人信息。" },
	"youtube-playlist": { title: "YouTube 播放列表链接入口", brief: "使用自己的公开短播放列表，展示列表标题、内容及分享列表链接入口。" },
	"youtube-batch": { title: "播放列表批量解析结果", brief: "展示列表内多条视频、选择方式和启动批量下载的真实入口。" },
	"instagram-profile": { title: "Instagram 个人主页链接入口", brief: "展示获授权公开账号的主页及复制或分享主页链接入口，不使用单条 Reels 的链接。" },
	"instagram-batch": { title: "Instagram 主页批量解析结果", brief: "展示主页解析出的作品列表、视频识别和批量下载入口。" },
	"tiktok-profile": { title: "TikTok 个人主页链接入口", brief: "展示自己的公开测试主页及复制主页链接入口，保留与单条视频分享的区别。" },
	"tiktok-batch": { title: "TikTok 主页批量解析结果", brief: "展示主页解析出的多个视频，以及选择和批量下载操作。" },
	"audio-process": { title: "在 Process 页面点击 Extract Audio（提取音频）", brief: "iPhone 17 Pro Max 模拟器真实截图，iOS 26.0。", src: "/assets/tutorials/extract-audio/process-orange.webp", width: 1319, height: 2748, framed: true, highlight: { x: 100, y: 1908, width: 346, height: 252 } },
	"audio-source": { title: "点击 Choose from Photos，从相册选择视频", brief: "选择视频来源；下载列表为空时也可以从相册导入。", src: "/assets/tutorials/extract-audio/select-source-orange.webp", width: 1319, height: 2748, framed: true },
	"audio-result": { title: "出现 Processing Complete，音频已生成为 M4A 文件", brief: "从相册视频实际提取的音频结果。", src: "/assets/tutorials/extract-audio/complete-orange.webp", width: 1319, height: 2748, framed: true },
	"audio-share": { title: "点击 Share File 后，可在分享面板找到保存到“文件”", brief: "真实分享面板，显示 M4A 文件、大小和保存入口。", src: "/assets/tutorials/extract-audio/share-orange.webp", width: 1319, height: 2748, framed: true },
	"join-process": { title: "点击底部 Process，再打开箭头所指的 Stitch Videos", brief: "真实工具总览，橙色外壳；箭头标注拼接入口。", src: "/assets/tutorials/extract-audio/process-orange.webp", width: 1319, height: 2748, framed: true, highlight: { x: 488, y: 722, width: 346, height: 252 } },
	"join-settings": { title: "Stitch Videos 参数页：先预览作为开头的主视频", brief: "真实模拟器截图，使用 AppStoreScreenshotFramer 橙色外壳。", src: "/assets/tutorials/join-videos/settings-orange.webp", width: 1319, height: 2748, framed: true },
	"join-source": { title: "Add Video 支持从下载列表、相册或文件添加片段", brief: "追加视频时的来源选择。", src: "/assets/tutorials/join-videos/add-source-orange.webp", width: 1319, height: 2748, framed: true },
	"join-order": { title: "2 clips added：主视频之后追加两段，用箭头调整顺序", brief: "已实测交换追加片段的顺序。", src: "/assets/tutorials/join-videos/order-orange.webp", width: 1319, height: 2748, framed: true },
	"join-progress": { title: "查看拼接进度，以及完成通知和取消选项", brief: "三段视频实际拼接过程。", src: "/assets/tutorials/join-videos/progress-orange.webp", width: 1319, height: 2748, framed: true },
	"join-result": { title: "预览拼接结果，再点击 Save to Photos 保存到相册", brief: "结果时长 11:46，已验证播放和保存成功提示。", src: "/assets/tutorials/join-videos/result-orange.webp", width: 1319, height: 2748, framed: true },
};

type Step = { title: string; text: string; image?: string; sections?: { title: string; text: string }[] };
export interface Tutorial {
	slug: string;
	category: (typeof categories)[number]["id"];
	title: string;
	description: string;
	intro: string;
	screenshotsReady?: boolean;
	verificationNote?: string;
	steps: Step[];
	tips: { title: string; text: string }[];
	faq: { question: string; answer: string }[];
	related: string[];
}

export const tutorials: Tutorial[] = [
	{
		slug: "extract-youtube-subtitles-iphone", category: "subtitles",
		screenshotsReady: true,
		title: "如何在 iPhone 和 iPad 上提取 YouTube 字幕？",
		description: "使用 ClipDock影随存提取 YouTube 已有字幕，选择语言和 SRT、VTT 等格式，保存到文件或分享，附五张真实操作截图。",
		intro: "把 YouTube 视频中已有的字幕单独保存下来，方便阅读、整理和后续使用。在 ClipDock影随存中粘贴视频链接，提取字幕后选择语言与格式，再导出即可。以下五张截图使用英文界面，可对照按钮旁的中文说明操作。",
		steps: [
			{ title: "粘贴 YouTube 视频链接", text: "先在 YouTube 中复制目标视频的分享链接。打开 ClipDock影随存，进入底部 Extract（提取）页面，切换到顶部 Subtitles（字幕）分页，再点击 Paste（粘贴）或手动填入链接。这里使用具体视频链接。", image: "subtitles-paste-link" },
			{ title: "开始提取，等待字幕列表", text: "确认链接后点击 Extract（提取）。按钮显示 Extracting captions…（正在提取字幕）时，等待提取完成。此功能只提取 YouTube 上已经存在的字幕，不会为没有字幕的视频自动转写音频。", image: "subtitles-extracting" },
			{ title: "选择需要的字幕语言", text: "完成后，页面显示视频缩略图、标题、时长和可用字幕轨道。点击每条字幕左侧的圆圈选择，可以单选、多选，或点击 Select all（全选）。截图中有 English (auto-generated)（英语自动生成字幕）和 English (United Kingdom)（英国英语）两条轨道；实际语言和数量取决于视频。", image: "subtitles-select-tracks" },
			{ title: "选择字幕文件格式", text: "点击 Format: SRT（格式：SRT）打开 Caption format（字幕格式）菜单。截图列出了 SRT、VTT、TTML、JSON3、SRV1、SRV2 和 SRV3。根据后续使用的软件选择格式，并核对所选轨道下方列出的可用格式。", image: "subtitles-select-format", sections: [
				{ title: "不知道选哪个格式？", text: "可以先选择 SRT；需要在网页播放器中使用时，可按播放器要求选择 VTT。若接收字幕的软件有明确要求，就选择其支持的格式。" },
			] },
			{ title: "导出到文件或分享", text: "确认语言和格式后，点击底部 Export captions（导出字幕）。括号中的数字表示选中的字幕轨道数，截图中选中了两条。弹出的 Export to（导出到）菜单提供 Save to Files（保存到文件）和 Share（分享）两个入口。", image: "subtitles-export", sections: [
				{ title: "保存到文件", text: "选择 Save to Files 后，按系统提示选择保存位置并确认，再打开“文件”App 检查导出的字幕文件。截图展示的是导出菜单，尚未展示保存完成状态。" },
				{ title: "分享给其他 App", text: "选择 Share，按系统分享面板的提示选择接收 App 或分享方式。导出的是字幕文件；只保存和使用你拥有权利或获得授权的内容。" },
			] },
		],
		tips: [
			{ title: "没有提取到字幕怎么办？", text: "先确认链接对应的视频能正常打开，并在 YouTube 中检查是否有字幕。没有现成字幕时，这个功能无法生成字幕；若视频已有字幕，可检查链接和网络后重试。" },
			{ title: "字幕内容有错误怎么办？", text: "自动生成字幕来自 YouTube，可能出现识别错误。导出后对照原视频检查人名、术语和时间轴，再用于后续整理。" },
		],
		faq: [
			{ question: "能提取自动生成的字幕吗？", answer: "可以提取视频提供的自动生成字幕。截图中的 English (auto-generated) 就是其中一条；是否可用以实际提取结果为准。" },
			{ question: "可以一次导出多种语言吗？", answer: "可以勾选多条字幕轨道，或点击 Select all 全选，再通过 Export captions 导出。可选语言以该视频已有字幕为准。" },
			{ question: "能自动翻译或给无字幕视频生成字幕吗？", answer: "本教程介绍的是提取 YouTube 已有字幕，界面没有展示翻译或音频转写功能。" },
			{ question: "字幕会保存到相册吗？", answer: "字幕是文件。请使用 Save to Files 保存到“文件”App，或通过 Share 分享到其他 App。" },
		],
		related: ["download-youtube-video-iphone", "download-youtube-playlist-iphone", "extract-audio-iphone"],
	},

	{
		slug: "download-tiktok-video-iphone", category: "platform",
		screenshotsReady: true,
		title: "2026 年如何在 iPhone 上下载 TikTok 视频并保存到相册？",
		description: "从 TikTok 分享链接开始，使用 ClipDock影随存提取视频、查看下载进度并保存到 iPhone 相册，附四张真实操作截图。",
		intro: "想把一条有权保存的 TikTok 视频留在手机里，可以先复制它的分享链接，再交给 ClipDock影随存识别。本文介绍单条视频的完整流程；iPad 用户也可以按相同思路操作。",
		steps: [
			{ title: "复制视频的分享链接", text: "在 TikTok 中打开目标视频，展开分享面板，点击 Copy link（复制链接）。复制的是这条视频的分享链接，而不是作者主页。本文截图使用英文界面，按钮旁的中文说明便于对照。", image: "tiktok-copy-orange" },
			{ title: "提交到 ClipDock影随存", text: "打开 ClipDock影随存的 Extract 页面，在 Video 分页中确认 Extract from Link 区域的链接。截图中 Fill from Clipboard 已开启，链接已从剪贴板填入；若输入框为空，可点击 Paste（粘贴）。确认后点击 Extract（提取）。", image: "tiktok-extract-orange" },
			{ title: "查看视频下载进度", text: "开始提取后，页面显示 Downloading（下载中）以及进度和文件大小。点击 View Task（查看任务）可以进入对应任务，也可以通过底部 Manager（管理）查看下载状态。等待任务进入 Done（已完成）后再打开视频。", image: "tiktok-progress-orange" },
			{ title: "预览并保存到相册", text: "在 Manager 的 Done 列表打开已完成的视频，点击播放按钮预览。确认内容正确后点击 Save to Photos（保存到相册）。若系统请求照片权限，按提示允许保存，再到照片 App 中检查结果。", image: "tiktok-photos-orange" },
		],
		tips: [{ title: "链接能打开，却没有识别结果", text: "确认该视频仍然公开可访问，再重新复制分享链接。登录限制、地区限制或来源页面变化都可能影响解析；连续重试并不一定能解决来源限制。" }],
		faq: [{ question: "为什么下载完成，却没出现在相册？", answer: "App 资料库和系统相册是两个位置。先确认任务完成，再从 App 执行保存到相册，并检查照片权限。" }, { question: "可以连着保存多个 TikTok 视频吗？", answer: "不同视频链接可以使用复制即下载流程；同一作者的作品则可以查看主页批量下载教程。两者的输入方式不同。" }],
		related: ["copy-tiktok-links-background", "batch-download-tiktok-profile-iphone", "video-to-live-photo-iphone"],
	},
	{
		slug: "download-douyin-video-iphone", category: "platform",
		screenshotsReady: true,
		title: "2026 年如何在 iPhone 上下载抖音视频并保存到相册？",
		description: "从抖音分享链接开始，使用 ClipDock影随存提取视频、查看下载进度并保存到 iPhone 相册，复用 TikTok 教程的四张截图演示操作流程。",
		intro: "想把一条有权保存的抖音视频留在手机里，可以先复制它的分享链接，再交给 ClipDock影随存识别。本文介绍单条视频的操作流程；iPad 用户也可以按相同思路操作。配图沿用 TikTok 教程，图中的平台名称、链接和视频素材仅作流程示意，并非抖音实测截图。",
		steps: [
			{ title: "复制视频的分享链接", text: "在抖音中打开目标视频，展开分享面板，点击“复制链接”。复制的是这条视频的分享链接，而不是作者主页。本步骤配图为 TikTok 的 Copy link 入口示意，抖音的实际按钮位置以当前界面为准。", image: "tiktok-copy-orange" },
			{ title: "提交到 ClipDock影随存", text: "打开 ClipDock影随存的 Extract 页面，在 Video 分页中确认 Extract from Link 区域的链接。截图中 Fill from Clipboard 已开启；操作时请填入你复制的抖音视频链接，若输入框为空，可点击 Paste（粘贴）。确认后点击 Extract（提取）。", image: "tiktok-extract-orange" },
			{ title: "查看视频下载进度", text: "开始提取后，页面显示 Downloading（下载中）以及进度和文件大小。点击 View Task（查看任务）可以进入对应任务，也可以通过底部 Manager（管理）查看下载状态。等待任务进入 Done（已完成）后再打开视频。", image: "tiktok-progress-orange" },
			{ title: "预览并保存到相册", text: "在 Manager 的 Done 列表打开已完成的视频，点击播放按钮预览。确认内容正确后点击 Save to Photos（保存到相册）。若系统请求照片权限，按提示允许保存，再到照片 App 中检查结果。", image: "tiktok-photos-orange" },
		],
		tips: [{ title: "链接能打开，却没有识别结果", text: "确认该视频仍然公开可访问，再重新复制分享链接。登录限制、地区限制或来源页面变化都可能影响解析；连续重试并不一定能解决来源限制。" }],
		faq: [{ question: "为什么下载完成，却没出现在相册？", answer: "App 资料库和系统相册是两个位置。先确认任务完成，再从 App 执行保存到相册，并检查照片权限。" }, { question: "图中的链接为什么不是抖音？", answer: "本文复用 TikTok 教程图片说明复制、提取、下载和保存步骤。实际操作时应使用自己的抖音视频链接，可下载资源以实际解析结果为准。" }],
		related: ["download-tiktok-video-iphone", "copy-link-auto-download-iphone", "extract-audio-iphone"],
	},
	{
		slug: "download-facebook-video-iphone", category: "platform",
		screenshotsReady: true,
		title: "如何在 iPhone 和 iPad 上下载 Facebook 视频与 Reels？",
		description: "从 Facebook 分享面板复制视频链接，使用 ClipDock影随存提取、选择画质、下载并保存到相册，附五张操作截图与格式说明。",
		intro: "想把 Facebook 视频保存到 iPhone 或 iPad，可以从作品的分享链接开始。本教程以一条 Reels 为例，展示复制链接、选择画质、下载与保存的步骤。以下五张截图使用英文界面，可对照中文按钮说明操作。",
		steps: [
			{ title: "复制 Facebook 视频链接", text: "在 Facebook 打开目标视频或 Reels，展开分享面板，在底部 Share to（分享至）一行点击 Copy link（复制链接）。复制当前作品的链接，供下一步提取使用。", image: "facebook-copy-link" },
			{ title: "粘贴链接并提取视频", text: "打开 ClipDock影随存，进入底部 Extract（提取）页面，在 Extract from Link 区域点击 Paste（粘贴），确认输入的是 Facebook 视频链接，再点击 Extract（提取）。截图中的链接包含 facebook.com/reel/；Fill from Clipboard 等自动化开关处于关闭状态，本次流程使用手动粘贴即可。", image: "facebook-extract-link" },
			{ title: "选择画质和文件格式", text: "提取后，在 Select Quality（选择清晰度）面板核对缩略图、清晰度、格式及预计大小。本例提供 1080p（WEBM，约 9.6 MB）、720p（MP4，约 6.8 MB）和 360p（MP4，约 909 KB）。选好后点击 Download（下载）。可选项目取决于实际解析结果。", image: "facebook-select-quality", sections: [
				{ title: "清晰度与体积一起考虑", text: "画质列表同时列出了分辨率和预计大小。想保留更多细节时可选较高清晰度；更在意传输时间和存储空间时，可选择较小的版本。预计大小不等于最终文件大小。" },
				{ title: "留意 MP4 与 WEBM", text: "本例的 1080p 标为 .webm，720p 和 360p 标为 .mp4。分辨率与文件格式是两件事，保存或交给其他 App 使用时，应同时核对格式及实际兼容情况。" },
				{ title: "是否设为默认画质", text: "底部 Set this quality as default and don't ask again 可将所选清晰度设为默认。希望每次比较画质、格式和大小时，可以像截图一样保持关闭。" },
			] },
			{ title: "查看下载进度", text: "开始下载后，页面显示 Downloading（下载中）、完成百分比、速度、预计剩余时间及已下载大小。点击 View Task（查看任务）或底部 Manager（管理）查看任务，等待下载完成。截图显示 94.58%，此时仍在下载。", image: "facebook-download-progress" },
			{ title: "预览视频并保存到相册", text: "在 Manager 的 Done（已完成）列表中打开视频。截图展示约 11 秒、9.04 MB 的结果及 Facebook 来源链接。点击播放检查画面和声音，再点击 Save to Photos（保存到相册），按系统提示完成保存，并到照片 App 中查看。", image: "facebook-save-photos", sections: [
				{ title: "下载完成与相册保存是两步", text: "Done 列表表示任务已下载到 App 内；还需要执行 Save to Photos，才能将视频保存到系统相册。本图展示保存入口，未展示保存成功提示。" },
			] },
		],
		tips: [{ title: "没有得到可下载结果", text: "先检查是否复制了当前视频的链接，并确认来源作品仍能访问。作品已删除或存在访问限制时，应先核对来源状态，再决定是否重试。" }],
		faq: [
			{ question: "本教程演示的是 Facebook Reels 吗？", answer: "是，截图中的来源链接为 facebook.com/reel/。处理其他 Facebook 视频时，也应复制具体作品链接；可下载资源以实际解析结果为准。" },
			{ question: "每个视频都能选择 1080p 吗？", answer: "不一定。1080p、720p 和 360p 是本例返回的选项，其他视频的可用清晰度、格式和大小可能不同。" },
			{ question: "下载完成后为什么在相册找不到？", answer: "先在 Manager 的 Done 列表打开视频，再点击 Save to Photos，并检查照片权限和保存提示。App 内的下载文件不会因为任务完成就自动出现在系统相册。" },
		],
		related: ["download-instagram-reels-iphone", "download-douyin-video-iphone", "extract-audio-iphone"],
	},
	{
		slug: "download-xiaohongshu-video-iphone", category: "platform",
		screenshotsReady: true,
		title: "如何在 iPhone 和 iPad 上下载小红书视频并保存到相册？",
		description: "复制小红书视频笔记的分享链接，使用 ClipDock影随存提取、下载并保存到相册，附四张操作配图及多项资源切换说明。",
		intro: "想把小红书视频笔记保存到 iPhone 或 iPad，可以先复制笔记的分享链接，再用 ClipDock影随存提取和下载。本文用四张配图说明完整操作顺序；分享面板中的联系人头像和用户名已做模糊处理。英文按钮旁附中文说明，方便对照。",
		steps: [
			{ title: "复制小红书视频笔记链接", text: "在小红书打开目标视频笔记，点击分享入口。在 Share to（分享至）面板底部找到 Copy link（复制链接），截图中位于最下排左起第二个。复制当前笔记的分享内容，供下一步粘贴使用。", image: "xiaohongshu-copy-link" },
			{ title: "粘贴分享内容并提取", text: "打开 ClipDock影随存，进入底部 Extract（提取）页面，在 Extract from Link 区域点击 Paste（粘贴）。本例输入框中既有“谁的 GT？！这车太帅了！”文案，也有小红书短链接。确认包含目标笔记链接后，点击 Extract（提取）。", image: "xiaohongshu-extract-link", sections: [
				{ title: "分享文案与链接可以一起粘贴", text: "本例保留了小红书分享文案，并完成了后续下载。粘贴后应确认链接也在其中，而不是只有标题文字；如果没有识别到链接，可重新复制，或只保留链接再尝试。" },
			] },
			{ title: "查看视频下载进度", text: "下载开始后，页面显示 Downloading（下载中）、完成百分比及已下载大小。本图显示 60.03%、2.44 MB / 4.06 MB，任务尚未完成。点击 View Task（查看任务）或底部 Manager（管理）查看状态，等待完成后再打开视频。", image: "xiaohongshu-download-progress" },
			{ title: "核对资源并保存到相册", text: "在 Manager 中打开已完成的视频，点击播放检查画面和声音。本图显示约 31 秒、4.06 MB 的视频，并保留小红书来源链接。确认后点击 Save to Photos（保存到相册），按系统提示完成保存，再到照片 App 中核对。", image: "xiaohongshu-save-photos", sections: [
				{ title: "用左右箭头切换资源", text: "预览页顶部显示 1 / 2，表示当前为两项资源中的第一项。可点击右箭头查看下一项，再决定保存哪一项；不要仅凭序号假定另一项的内容或格式。实际资源数量以结果页为准。" },
				{ title: "下载完成后还要保存", text: "下载到 App 内与保存到系统相册是两个步骤。若相册里找不到视频，先确认已点击 Save to Photos，并检查照片权限及保存提示。本图展示保存入口，没有展示保存成功提示。" },
			] },
		],
		tips: [{ title: "粘贴后没有提取结果", text: "检查分享内容是否包含完整链接，并确认来源笔记仍能打开。若笔记已删除或存在访问限制，应先核对来源状态。" }],
		faq: [
			{ question: "需要先删掉分享文案吗？", answer: "本例带着文案和短链接一起粘贴，并完成了下载。若遇到链接识别问题，可以重新复制或只保留链接重试。" },
			{ question: "每条笔记都会出现两项资源吗？", answer: "不一定。1 / 2 是这次结果页的显示，其他笔记的资源数量和内容以实际解析结果为准。" },
			{ question: "这篇也演示了图文笔记下载吗？", answer: "没有，本文截图演示的是视频笔记，不把本例的结果视为图文笔记流程。" },
		],
		related: ["download-douyin-video-iphone", "download-facebook-video-iphone", "extract-audio-iphone"],
	},
	{
		slug: "download-bilibili-video-iphone", category: "platform",
		screenshotsReady: true,
		title: "如何在 iPhone 和 iPad 上下载 Bilibili（B 站）视频并保存到相册？",
		description: "复制 B 站单条视频分享链接，使用 ClipDock影随存提取、选择清晰度、下载并保存到相册，附五张操作截图。",
		intro: "想把一条 B 站视频保存到 iPhone 或 iPad，可以从视频页面复制分享链接，再交给 ClipDock影随存提取。本文以“背景音乐版”视频为例，说明选择画质、查看下载进度和预览保存的步骤。",
		steps: [
			{ title: "复制 B 站视频分享链接", text: "在 Bilibili 打开目标视频，展开分享面板，点击“复制链接”。截图中该按钮位于“微博”右侧。这里复制的是具体视频页面的链接；需要同一 UP 主的多条投稿时，可改用主页批量下载教程。", image: "bilibili-copy-link-orange" },
			{ title: "粘贴链接并提取视频", text: "打开 ClipDock影随存，进入底部 Extract（提取）页面，选择顶部 Video（视频）分页。在 Extract from Link 区域点击 Paste（粘贴），核对链接后点击 Extract（提取）。本例直接粘贴 b23.tv 开头的分享短链接，自动填入和自动下载开关保持关闭即可完成这套手动流程。", image: "bilibili-extract-link-orange" },
			{ title: "选择清晰度并开始下载", text: "在 Select Quality（选择清晰度）面板核对缩略图和“背景音乐版”标题，再选择画质。本例选中 1080p MP4，预计 55.3 MB；还显示 720p MP4（约 27.5 MB）、480p MP4（约 17.8 MB）和下方的 360p 入口。选好后点击 Download（下载）。", image: "bilibili-select-quality-orange", sections: [
				{ title: "结合清晰度与文件大小选择", text: "较高清晰度通常能保留更多画面细节，也可能占用更多空间。根据观看需求比较列表中的预计大小；这些数值属于本例，其他视频的可选画质和体积以实际解析结果为准。" },
				{ title: "是否设置默认画质", text: "底部 Set this quality as default and don't ask again 用于将所选清晰度设为默认。希望每次都比较画质和大小时，可像截图一样保持关闭。" },
			] },
			{ title: "查看视频下载进度", text: "下载开始后，页面显示 Downloading（下载中）、进度百分比、速度、预计剩余时间和已下载大小。本图为 15.00%，仍需等待。点击 View Task（查看任务）或底部 Manager（管理），查看对应任务的状态。", image: "bilibili-download-progress-orange" },
			{ title: "预览视频并保存到相册", text: "在 Manager 的 Done（已完成）列表打开目标视频。本图的标题为“背景音乐版”，显示时长约 8 分 55 秒、大小 46.44 MB，预览停在 00:56，并保留原始来源链接。点击播放检查画面和声音，再点击 Save to Photos（保存到相册），按系统提示完成保存。", image: "bilibili-save-photos-orange", sections: [
				{ title: "以最终文件信息为准", text: "画质面板的预计大小、下载过程中的大小与最终文件大小可能不同。本例结果页显示 46.44 MB，应结合实际文件和播放效果核对。" },
				{ title: "1 / 63 是预览列表位置", text: "结果页上方显示 1 / 63，背景的 Done 列表也有 63 项。这个序号不表示本条视频有 63 个分 P；用标题与来源链接确认当前文件，左右箭头用于切换预览条目。" },
				{ title: "下载到 App 后还需保存到相册", text: "Done 表示任务已完成，不等于已保存到系统相册。点击 Save to Photos 后检查保存提示和照片权限，再到照片 App 中查看。本图展示保存入口，未展示保存成功提示。" },
			] },
		],
		tips: [{ title: "下载前核对视频版本", text: "本例返回的标题是“背景音乐版”。如果原页面有不同版本或分集，应核对实际返回的标题、缩略图和下载后的内容，避免保存了不需要的版本。" }],
		faq: [
			{ question: "可以直接使用 b23.tv 短链接吗？", answer: "本例从视频分享面板复制 b23.tv 短链接，直接粘贴并完成下载。请确认短链接来自目标视频。" },
			{ question: "每条视频都支持 1080p 吗？", answer: "不一定。1080p 是本例提供的画质，可选清晰度以实际解析结果为准。" },
			{ question: "这篇演示了全部分 P 下载吗？", answer: "没有，本组截图展示的是单条视频的提取与下载，不据此推断全部分 P 都会下载。" },
			{ question: "如何批量下载 UP 主的其他视频？", answer: "复制 UP 主主页链接，在 Batch 分页加载作品列表，具体步骤可查看 B 站主页批量下载教程。" },
		],
		related: ["batch-download-bilibili-profile-iphone", "extract-audio-iphone", "trim-video-iphone"],
	},
	{
		slug: "download-youtube-video-iphone", category: "platform",
		screenshotsReady: true,
		title: "2026 年如何在 iPhone 和 iPad 上下载 YouTube 视频？",
		description: "使用 ClipDock影随存在 iPhone 和 iPad 上提取 YouTube 视频、选择清晰度、查看下载进度并保存到相册，附五张真实操作截图。",
		intro: "这篇教程针对一条 YouTube 视频的保存。先从具体视频取得分享链接，再查看 ClipDock影随存返回的资源；若你要保存整个播放列表，请使用对应的批量教程。",
		steps: [
			{ title: "复制 YouTube 视频链接", text: "在 YouTube 中打开目标视频，点击分享按钮，在分享面板中选择 Copy link（复制链接）。这里复制的是当前视频的链接；如果要保存播放列表，请使用对应的批量下载教程。本文截图为英文界面，可对照按钮旁的中文说明操作。", image: "youtube-copy-orange" },
			{ title: "提交链接并提取视频", text: "打开 ClipDock影随存的 Extract 页面，在 Video 分页找到 Extract from Link 区域。点击 Paste（粘贴）填入链接；如果链接已经从剪贴板填入，确认后直接点击 Extract（提取）。", image: "youtube-extract-orange" },
			{ title: "选择清晰度并开始下载", text: "提取后，在 Select Quality（选择清晰度）面板中选择所需画质。截图中的示例提供 1080p、720p、480p 等选项，并显示 MP4 格式与预计大小。确认选项后点击 Download（下载）。若希望以后使用同一画质，可开启底部的默认清晰度开关；可用画质以每次实际解析结果为准。", image: "youtube-quality-orange" },
			{ title: "查看下载进度", text: "下载开始后，页面会显示 Downloading（下载中）、百分比、下载速度、预计剩余时间和已下载大小。点击 View Task（查看任务）或底部 Manager（管理）查看任务，等待下载完成。", image: "youtube-progress-orange" },
			{ title: "预览并保存到相册", text: "在 Manager 中打开已完成的视频，点击播放按钮检查画面和声音。如果结果页包含多项资源，可用左右箭头切换并确认目标视频。点击 Save to Photos（保存到相册），按需允许照片权限，再到照片 App 中查看保存结果。", image: "youtube-photos-orange" },
		],
		tips: [{ title: "下载的文件没有声音", text: "先检查选中的资源类型，再尝试其他实际可用的视频资源。只有在你另有对应音轨时，音视频合并工具才有可用的音频输入。" }],
		faq: [{ question: "能直接下载整个频道吗？", answer: "频道属于批量解析任务，不是单视频下载。要使用频道或列表入口，并以实际返回的可用作品为准。" }, { question: "能保证所有视频都有高清资源吗？", answer: "不能。可用资源受源文件、平台响应和访问条件影响，以识别结果为准。" }],
		related: ["download-youtube-playlist-iphone", "extract-audio-iphone", "copy-link-auto-download-iphone"],
	},
	{
		slug: "download-instagram-reels-iphone", category: "platform",
		screenshotsReady: true,
		title: "2026 年如何在 iPhone 上下载 Instagram Reels？",
		description: "使用 ClipDock影随存在 iPhone 或 iPad 上下载 Instagram Reels，从复制分享链接、提取视频到保存相册，附四张真实操作截图。",
		intro: "保存一条 Instagram Reels，关键是取得作品本身的分享链接。这篇从单条 Reels 的复制链接入口讲起，再完成识别、下载与相册保存。",
		steps: [
			{ title: "复制 Reels 的作品链接", text: "在 Instagram 打开目标 Reels，点击分享按钮，在分享面板底部选择 Copy link（复制链接）。这里复制的是当前作品的链接，而不是作者主页。本文截图为英文界面，可对照按钮旁的中文说明操作。", image: "instagram-copy-orange" },
			{ title: "提交链接并提取视频", text: "打开 ClipDock影随存的 Extract 页面，在 Video 分页找到 Extract from Link 区域。截图中链接已从剪贴板自动填入；如果输入框为空，点击 Paste（粘贴）。确认是目标 Reels 的链接后，点击 Extract（提取）。", image: "instagram-extract-orange" },
			{ title: "查看下载进度", text: "下载开始后，页面显示 Downloading（下载中）、完成百分比和已下载大小。点击 View Task（查看任务）或底部 Manager（管理）查看任务，等待视频下载完成。", image: "instagram-progress-orange" },
			{ title: "预览并保存到相册", text: "在 Manager 中打开已完成的视频，点击播放按钮检查画面和声音。如果预览页有多项资源，可用左右箭头切换，确认要保存的视频。点击 Save to Photos（保存到相册），按需允许照片权限，再到照片 App 中查看结果。", image: "instagram-photos-orange" },
		],
		tips: [{ title: "私密账号或已失效作品", text: "一个链接并不等于访问授权。若来源要求特定登录权限、作品已删除或链接已失效，公开链接流程可能无法取得资源。" }],
		faq: [{ question: "这个流程也适用于 Instagram Story 吗？", answer: "本文仅针对 Reels。Story 的链接、有效时间和访问条件不同，不应把单条 Reels 的结果当作 Story 支持证明。" }, { question: "如何保存同一作者的多条视频？", answer: "使用作者主页链接走批量解析流程，详见 Instagram 主页批量下载教程。" }],
		related: ["batch-download-instagram-profile-iphone", "copy-link-auto-download-iphone", "video-to-live-photo-iphone"],
	},
	{
		slug: "download-x-twitter-video-iphone", category: "platform",
		screenshotsReady: true,
		title: "2026 年如何在 iPhone 上下载 X（Twitter）视频？",
		description: "使用 ClipDock影随存在 iPhone 或 iPad 上下载 X（Twitter）视频，从复制帖子链接、选择清晰度到保存相册，附五张真实操作截图。",
		intro: "在 X 上看到需要保存的视频时，应复制包含该视频的帖子链接。昵称、个人主页和文字截图都不能代替目标帖子的地址。",
		steps: [
			{ title: "复制含视频的帖子链接", text: "在 X 中打开目标帖子，点击分享按钮，在面板底部选择 Copy Link（复制链接）。截图中央显示的是 X Chat 设置提示，复制链接入口位于左下角，不是中央的 Set up 按钮。本文截图为英文界面，可对照中文说明操作。", image: "x-copy-orange" },
			{ title: "提交链接并提取视频", text: "打开 ClipDock影随存的 Extract 页面，在 Video 分页找到 Extract from Link 区域。点击 Paste（粘贴）填入帖子链接；如果链接已经填入，确认后直接点击 Extract（提取）。", image: "x-extract-orange" },
			{ title: "选择清晰度并开始下载", text: "提取后，在 Select Quality（选择清晰度）面板中核对视频缩略图并选择画质。截图中的示例提供 720p、480p 和 360p 的 MP4 选项，并显示预计大小。点击 Download（下载）开始保存；可用画质以实际解析结果为准。底部开关可将所选清晰度设为默认。", image: "x-quality-orange" },
			{ title: "查看下载进度", text: "下载开始后，页面显示 Downloading（下载中）、完成百分比、下载速度、预计剩余时间和已下载大小。点击 View Task（查看任务）或底部 Manager（管理）查看任务，等待下载完成。", image: "x-progress-orange" },
			{ title: "预览并保存到相册", text: "在 Manager 中打开已完成的视频，点击播放按钮检查画面和声音。如果预览页有多项资源，可用左右箭头切换，确认目标视频。点击 Save to Photos（保存到相册），按需允许照片权限，再到照片 App 中查看保存结果。", image: "x-photos-orange" },
		],
		tips: [{ title: "帖子有媒体，但不是想要的视频", text: "先检查链接指向的是原帖、引用帖还是个人主页。不要仅凭帖子文字判断，应该以最终识别的实际媒体为准。" }],
		faq: [{ question: "账号需要登录才能查看怎么办？", answer: "这类内容可能受访问条件限制。复制链接本身不能绕过登录、私密账号或其他访问控制。" }, { question: "能下载后直接提取声音吗？", answer: "可以对已保存且含音轨的视频使用音频提取工具，具体输出格式以工具实际提供的选项为准。" }],
		related: ["copy-link-auto-download-iphone", "extract-audio-iphone", "download-tiktok-video-iphone"],
	},
	{
		slug: "copy-link-auto-download-iphone", category: "clipboard",
		screenshotsReady: true,
		title: "iPhone 如何只复制链接就下载视频？无需反复切换 App",
		description: "了解 ClipDock影随存复制即下载的准备流程、单条验证和完成通知，减少在来源 App 与下载器之间来回粘贴。",
		intro: "复制即下载适合从不同作品中逐条挑选视频：你在来源 App 复制分享链接，ClipDock影随存在功能已就绪时识别并创建任务。它和一次解析整个主页的批量下载是两种不同流程。",
		steps: [
			{ title: "开启复制即下载与后台检测", text: "打开 ClipDock影随存的 Extract 页面，在 Video 分页开启 Fill from Clipboard（从剪贴板填入）、Auto-download Links（自动下载链接）和 Detect in Background（后台检测），如图中的三个绿色开关。", image: "clipboard-enable-orange" },
			{ title: "切到视频平台，保持悬浮窗开启", text: "切换到 TikTok 等视频平台，确认屏幕上出现 ClipDock影随存的画中画悬浮窗。图中 Copy a link to download 提示表示可以开始复制链接；可以将悬浮窗滑动到屏幕边缘收起，但请保持画中画开启，不要关闭悬浮窗。", image: "clipboard-pip-orange" },
			{ title: "复制想保存的视频链接", text: "刷到喜欢的视频后打开分享面板，点击 Copy link（复制链接），不需要再回到 ClipDock影随存粘贴。悬浮窗提示可以滑到屏幕边缘收起，但要保持画中画开启。", image: "clipboard-copy-orange" },
			{ title: "边刷边复制，查看后台下载提示", text: "观看录屏中的连续操作：复制分享链接后，ClipDock影随存在后台识别资源并创建下载任务，你可以继续浏览其他视频。留意系统通知中的任务状态；浏览结束后，到 Manager（管理）检查结果，需要相册副本时再执行保存到相册。", image: "clipboard-demo" },
		],
		tips: [{ title: "复制了链接，却没有自动下载", text: "依次检查功能状态、链接是否支持、网络连接以及系统提示。手动粘贴也失败时，问题更可能在来源链接；手动可用而自动没有响应时，应优先检查复制即下载的运行条件。" }],
		faq: [{ question: "关闭 App 或锁屏后一定能继续识别吗？", answer: "不能把后台功能理解为无条件常驻。锁屏、强制退出和系统资源调度下的具体表现，需要按照当前 App 版本和实际测试确认。" }, { question: "复制即下载等于批量解析主页吗？", answer: "不等于。前者接收你逐条复制的分享链接，后者从一个主页或列表链接提取多条作品。" }],
		related: ["copy-tiktok-links-background", "download-youtube-playlist-iphone", "download-x-twitter-video-iphone"],
	},
	{
		slug: "copy-tiktok-links-background", category: "clipboard",
		screenshotsReady: true,
		title: "如何边刷 TikTok 边复制链接下载视频？",
		description: "在 TikTok 中逐条挑选视频，通过 ClipDock影随存复制即下载创建任务，了解如何验证接收、查看完成通知和避免漏掉链接。",
		intro: "收藏来自不同作者的几条视频时，逐条复制分享链接比解析完整主页更符合选择过程。先让 ClipDock影随存的复制即下载功能就绪，再回到 TikTok 浏览和挑选。",
		steps: [
			{ title: "开启自动下载与后台检测", text: "在 ClipDock影随存的 Extract 页面打开 Video 分页，开启 Fill from Clipboard（从剪贴板填入）、Auto-download Links（自动下载链接）和 Detect in Background（后台检测），确认三个开关均为绿色。", image: "clipboard-enable-orange" },
			{ title: "回到 TikTok，确认悬浮窗已出现", text: "切回 TikTok 浏览视频，保持 ClipDock影随存的画中画悬浮窗开启。看到 Copy a link to download（复制链接即可下载）提示后，就可以开始挑选想保存的作品。", image: "clipboard-pip-orange" },
			{ title: "打开分享面板并复制链接", text: "在目标视频上点击分享按钮，选择 Copy link（复制链接），然后继续浏览。不需要来回切换 App；若悬浮窗挡住画面，可以按提示滑到屏幕边缘收起，保持画中画开启。", image: "clipboard-copy-orange" },
			{ title: "观看连续复制与后台下载演示", text: "录屏展示了边刷 TikTok 边复制多个作品链接的过程，以及后台识别、创建下载任务的通知。确认第一条链接已接收后再继续收集；浏览结束后到 Manager 检查完成与失败任务，避免只凭通知判断结果。", image: "clipboard-demo" },
		],
		tips: [{ title: "什么时候改用主页批量下载？", text: "如果目标是同一作者的一组作品，复制主页链接更合适。如果只想选取来自多个作者的少量作品，继续使用逐条复制流程。" }],
		faq: [{ question: "为什么这篇和普通 TikTok 下载教程分开？", answer: "普通教程是复制后回 App 手动提交；这里重点是首次准备、自动接收验证和连续收集的过程。" }, { question: "复制时有系统权限提示怎么办？", answer: "按当前系统和 App 的提示理解并处理权限。不要默认忽略提示后功能仍然正常，也不需要提供账号密码给教程。" }],
		related: ["copy-link-auto-download-iphone", "batch-download-tiktok-profile-iphone", "download-tiktok-video-iphone"],
	},
	{
		slug: "download-youtube-playlist-iphone", category: "batch",
		screenshotsReady: true,
		title: "2026 年如何在 iPhone/iPad 上批量下载 YouTube 播放列表？",
		description: "取得 YouTube 播放列表链接，在 ClipDock影随存中解析多条视频、确认结果并创建批量任务，处理缺失条目和下载失败。",
		intro: "播放列表批量下载的输入是一份列表，而不是其中某个视频。适合备份自己的系列作品或已获授权的课程片段，减少逐条复制视频链接的操作。",
		steps: [
			{ title: "在 Batch 分页填入播放列表链接", text: "复制 YouTube 播放列表的分享链接，打开 ClipDock影随存的 Extract 页面，切换到 Batch（批量）分页，点击 Paste（粘贴）填入。确认使用的是播放列表链接，而不是单个视频的地址。", image: "playlist-input-orange" },
			{ title: "加载播放列表", text: "点击 Load list（加载列表），等待 Loading list 提示结束。加载列表只是获取可选择的作品，不会立即开始下载；下一步还需要选择条目并加入队列。", image: "playlist-loading-orange" },
			{ title: "选择视频并加入下载队列", text: "核对列表中的视频，使用 All、Video、Image 筛选类型，点击条目右侧的勾选按钮调整选择，或用 Select loaded 选择已加载条目。通过 Batch quality 设置批量画质；截图中跟随下载设置。确认后点击 Add to queue（加入队列）。示例选中了 24 项，实际数量以加载结果为准。", image: "playlist-select-orange" },
			{ title: "查看排队状态与下载进度", text: "打开底部 Manager（管理），在 Active 中查看本次任务。Queued 表示排队等待，开始下载后会显示进度、速度和预计剩余时间。通过 Done 查看已完成任务，通过 Failed 检查失败任务；图中 Active 24 表示仍在处理的 24 项，并非全部下载完成。", image: "playlist-queue-orange" },
		],
		tips: [{ title: "解析数量与列表显示数量不一致", text: "先检查是否有不可访问的作品，再确认是否复制了正确的列表链接。列表显示数量不等于本次实际可下载数量，不要盲目重复提交整份列表。" }],
		faq: [{ question: "播放列表教程能直接当频道下载教程使用吗？", answer: "不能完全等同。两者都属于批量任务，但输入页面和覆盖作品范围不同，应检查实际解析结果。" }, { question: "批量完成后会自动进入相册吗？", answer: "应先查看 App 的实际保存位置。下载到资料库与导出到系统相册是两件事。" }],
		related: ["download-youtube-video-iphone", "join-videos-iphone", "batch-download-tiktok-profile-iphone"],
	},
	{
		slug: "batch-download-instagram-profile-iphone", category: "batch",
		screenshotsReady: true,
		title: "如何在 iPhone 和 iPad 上批量下载 Instagram 主页视频与图片？",
		description: "复制 Instagram 主页链接，在 ClipDock影随存加载作品列表，筛选视频或图片、设置批量画质并加入下载队列，附五张操作截图。",
		intro: "保存同一个 Instagram 作者的多条作品，可以先加载主页列表，再选择需要的视频与图片。本文通过五张截图说明主页链接、列表加载、资源选择和下载队列；iPad 用户也可对照操作。",
		steps: [
			{ title: "复制 Instagram 主页链接", text: "在 Instagram 打开目标作者的个人主页，点击右上角省略号，在菜单中选择 Copy profile URL（复制主页链接）。这里需要作者主页地址；只下载某一条 Reels 时，可使用单条视频教程。", image: "instagram-batch-profile-orange" },
			{ title: "在 Batch 分页粘贴链接", text: "打开 ClipDock影随存，进入底部 Extract（提取）页面，切换顶部 Batch（批量）分页。点击 Paste（粘贴）填入主页链接，并核对账号地址。页面 Guide 说明了复制列表链接、加载选择和加入队列三个阶段。", image: "instagram-batch-input-orange" },
			{ title: "加载主页作品列表", text: "点击 Load list（加载列表），等待 Loading list（正在加载列表）提示结束。加载列表只是获取可供选择的作品，还不会开始下载；下一步确认选择并加入队列后才会创建下载任务。", image: "instagram-batch-loading-orange" },
			{ title: "筛选资源并加入下载队列", text: "列表返回后先核对作者名称。本例显示 1 pages、12 posts、16 items，当前选中 16 项。根据需要选择资源，核对底部 Add to queue（加入队列）括号中的数量后再点击。", image: "instagram-batch-select-orange", sections: [
				{ title: "All、Video、Image：按媒体类型筛选", text: "All 显示全部类型，Video 筛选视频，Image 筛选图片。只需要视频时切换 Video，并在提交前核对条目勾选状态和总选择数，避免将不需要的图片一起加入队列。" },
				{ title: "帖子数与资源数为什么不同？", text: "一个帖子可能包含多项媒体。截图中的图片分别标有 1/5、2/5、3/5，因此 12 条帖子可以对应 16 项资源。这里是已加载的结果，不代表作者主页的全部历史作品。" },
				{ title: "逐项选择与 Select loaded", text: "条目右侧的蓝色勾选表示已选中，可按需调整。Select loaded 用于选择已加载的条目；以页面显示的选择数量为准。Change link 可用于更换主页链接。" },
				{ title: "Batch quality：批量画质", text: "截图显示 Follow download settings（跟随下载设置），表示本批次采用下载设置中的画质偏好。需要调整时点击 Batch quality 查看当前版本提供的选项，再确认下载范围。" },
			] },
			{ title: "在 Manager 检查任务状态", text: "加入队列后进入 Manager（管理）。本图显示 Active 16，列表中既有 Queued（排队中）条目，也有正在下载的视频及进度百分比。任务完成后到 Done（已完成）列表预览结果；需要保存到系统相册时，再从结果页执行 Save to Photos。", image: "instagram-batch-queue-orange", sections: [
				{ title: "排队不等于下载完成", text: "Queued 表示等待处理；进度条、速度和剩余时间表示正在下载。截图展示的是队列运行状态，不能据此认为这 16 项已经全部下载或保存到相册。" },
			] },
		],
		tips: [{ title: "先核对已加载范围", text: "主页列表以实际返回结果为准，不代表 Story、私密内容、已删除内容或全部历史作品都会包含在内。批量提交前先确认作者、媒体类型和选择数量。" }],
		faq: [
			{ question: "只下载视频，可以不下载图片吗？", answer: "可以通过 Video 筛选查看视频，并核对条目选择状态及 Add to queue 的数量后提交。本例截图选中了包含视频和图片的 16 项资源。" },
			{ question: "点击 Load list 就会下载吗？", answer: "不会。加载后还需要选择条目，并点击 Add to queue 才会加入下载队列。" },
			{ question: "为什么显示 12 posts，却有 16 items？", answer: "帖子与媒体资源不是同一计数单位，多图帖子可以包含多项图片资源。实际下载数量看选中项和加入队列按钮。" },
			{ question: "截图中的 Unlimited 代表所有用户都不限量吗？", answer: "不能这样推断。这是截图时的界面状态，可选数量和使用限制以当前账号及版本显示为准。" },
		],
		related: ["download-instagram-reels-iphone", "download-youtube-playlist-iphone", "join-videos-iphone"],
	},
	{
		slug: "batch-download-tiktok-profile-iphone", category: "batch",
		screenshotsReady: true,
		title: "如何在 iPhone 和 iPad 上批量下载 TikTok 主页视频？",
		description: "复制 TikTok 作者主页链接，在 ClipDock影随存加载作品列表，筛选资源、设置批量画质并加入下载队列，附五张操作截图。",
		intro: "需要保存同一个 TikTok 作者的多条作品时，可以从主页链接开始，在 Batch 分页加载列表后选择需要的资源。本文用五张截图说明从复制主页链接到查看下载队列的流程。",
		steps: [
			{ title: "复制作者主页链接", text: "在 TikTok 打开目标作者主页，点击右上角分享箭头，在 Send to（发送至）面板中点击 Copy link（复制链接）。这里复制的是作者主页，不是单条视频链接。", image: "tiktok-batch-profile-orange" },
			{ title: "在 Batch 分页粘贴主页地址", text: "打开 ClipDock影随存的 Extract（提取）页面，切换顶部 Batch（批量）分页，点击 Paste（粘贴）。本例显示 tiktok.com/@hyz00_ 的主页地址，确认作者正确后准备加载列表。", image: "tiktok-batch-input-orange" },
			{ title: "加载列表并等待结果", text: "点击 Load list（加载列表），等待 Loading list（正在加载列表）结束。这个阶段只加载可选择的资源，还没有开始下载；需要在下一步确认条目并点击 Add to queue。", image: "tiktok-batch-loading-orange" },
			{ title: "选择资源、画质并加入队列", text: "核对列表顶部的作者名称。本例显示 1 pages、33 posts、42 items，并选中了 42 项资源。检查条目后，点击 Add to queue（加入队列）；按钮括号内显示本次选择数量。", image: "tiktok-batch-select-orange", sections: [
				{ title: "All、Video、Image：筛选媒体类型", text: "All 查看全部资源，Video 查看视频，Image 查看图片。需要只下载视频时先切换 Video，再核对勾选状态和提交数量。条目右侧蓝色勾选表示已选中，可按需调整。" },
				{ title: "Select loaded 与已加载范围", text: "Select loaded 用于选择已加载的条目。posts 是帖子数，items 是资源数，一个帖子可能包含多项媒体，因此两者不一定相同。当前列表不等于作者的全部历史作品；要更换作者可点击 Change link。" },
				{ title: "Batch quality：批量画质", text: "本例显示 Follow download settings（跟随下载设置），采用下载设置中的画质偏好。需要修改时点击 Batch quality 查看可用选项，确认后再加入队列。" },
				{ title: "数量与账号限制以界面为准", text: "截图中的 42 selected 和 Unlimited 是本例状态，不代表所有账号、所有主页都能返回相同数量或无限下载。提交前以自己的界面为准。" },
			] },
			{ title: "查看下载进度和失败任务", text: "进入 Manager（管理）检查任务。截图显示 Active 41、Done 14、Failed 1，列表中同时有 Queued（排队中）和正在下载的条目。这些是管理器当前的统计，不能直接当成本批 42 项的完成结果。", image: "tiktok-batch-queue-orange", sections: [
				{ title: "排队、下载中与已完成", text: "Queued 表示等待处理，进度条表示正在下载。到 Done 列表打开已完成的文件，预览画面和声音；需要保存到相册时再执行 Save to Photos。本组截图未展示全部任务完成或保存成功。" },
				{ title: "有失败条目时怎么检查", text: "进入 Failed 核对具体任务及错误信息，再检查链接和网络。截图没有展开失败详情，无法仅凭 Failed 1 判断失败原因，或确定它属于本批次。" },
			] },
		],
		tips: [{ title: "先选择需要的作品", text: "同一作者的多条作品适合主页批量下载；只需要某条视频时，使用单条视频链接更容易确认目标。再次提交主页前核对已下载内容，避免重复。" }],
		faq: [
			{ question: "加载主页列表就会开始下载吗？", answer: "不会。需要选中资源，核对画质和数量，再点击 Add to queue。" },
			{ question: "主页上的所有作品都会出现在列表里吗？", answer: "不保证。以实际加载的资源为准，不把列表视为全部历史内容或受限内容的完整备份。" },
			{ question: "为什么有些条目只显示 Resource？", answer: "这是本例列表返回的显示名称。可以结合缩略图、媒体类型和日期核对，下载后再预览确认，不能仅凭通用标题判断内容。" },
		],
		related: ["download-tiktok-video-iphone", "batch-download-douyin-profile-iphone", "batch-download-instagram-profile-iphone"],
	},
	{
		slug: "batch-download-douyin-profile-iphone", category: "batch",
		screenshotsReady: true,
		title: "如何在 iPhone 和 iPad 上批量下载抖音主页视频？",
		description: "复制抖音作者主页链接，在 ClipDock影随存加载作品列表，筛选资源、设置批量画质并加入下载队列，复用 TikTok 的五张截图说明流程。",
		intro: "需要保存同一个抖音作者的多条作品时，可以从主页链接开始，在 Batch 分页加载列表后选择需要的资源。本文复用 TikTok 的五张截图说明操作流程，图中的账号、链接和任务数量仅作示意，并非抖音实测记录。实际操作时请使用抖音主页链接。",
		steps: [
			{ title: "复制作者主页链接", text: "在抖音打开目标作者主页，从主页分享入口选择“复制链接”。配图展示 TikTok 的 Send to / Copy link，抖音按钮位置以当前界面为准。这里复制的是作者主页，不是单条视频链接。", image: "tiktok-batch-profile-orange" },
			{ title: "在 Batch 分页粘贴主页地址", text: "打开 ClipDock影随存的 Extract（提取）页面，切换顶部 Batch（批量）分页，点击 Paste（粘贴）。配图中的 tiktok.com 地址仅作示意；请粘贴你复制的抖音主页链接，确认作者正确后准备加载列表。", image: "tiktok-batch-input-orange" },
			{ title: "加载列表并等待结果", text: "点击 Load list（加载列表），等待 Loading list（正在加载列表）结束。这个阶段只加载可选择的资源，还没有开始下载；需要在下一步确认条目并点击 Add to queue。", image: "tiktok-batch-loading-orange" },
			{ title: "选择资源、画质并加入队列", text: "核对列表顶部的作者名称。示意图显示 1 pages、33 posts、42 items，并选中了 42 项资源；你的抖音主页返回数量可能不同。检查条目后，点击 Add to queue（加入队列）；按钮括号内显示本次选择数量。", image: "tiktok-batch-select-orange", sections: [
				{ title: "All、Video、Image：筛选媒体类型", text: "All 查看全部资源，Video 查看视频，Image 查看图片。需要只下载视频时先切换 Video，再核对勾选状态和提交数量。条目右侧蓝色勾选表示已选中，可按需调整。" },
				{ title: "Select loaded 与已加载范围", text: "Select loaded 用于选择已加载的条目。posts 是帖子数，items 是资源数，一个帖子可能包含多项媒体，因此两者不一定相同。当前列表不等于作者的全部历史作品；要更换作者可点击 Change link。" },
				{ title: "Batch quality：批量画质", text: "本例显示 Follow download settings（跟随下载设置），采用下载设置中的画质偏好。需要修改时点击 Batch quality 查看可用选项，确认后再加入队列。" },
				{ title: "数量与账号限制以界面为准", text: "截图中的 42 selected 和 Unlimited 是本例状态，不代表所有账号、所有主页都能返回相同数量或无限下载。提交前以自己的界面为准。" },
			] },
			{ title: "查看下载进度和失败任务", text: "进入 Manager（管理）检查任务。截图显示 Active 41、Done 14、Failed 1，列表中同时有 Queued（排队中）和正在下载的条目。这些是管理器当前的统计，不能直接当成本批 42 项的完成结果。", image: "tiktok-batch-queue-orange", sections: [
				{ title: "排队、下载中与已完成", text: "Queued 表示等待处理，进度条表示正在下载。到 Done 列表打开已完成的文件，预览画面和声音；需要保存到相册时再执行 Save to Photos。本组截图未展示全部任务完成或保存成功。" },
				{ title: "有失败条目时怎么检查", text: "进入 Failed 核对具体任务及错误信息，再检查链接和网络。截图没有展开失败详情，无法仅凭 Failed 1 判断失败原因，或确定它属于本批次。" },
			] },
		],
		tips: [{ title: "先选择需要的作品", text: "同一作者的多条作品适合主页批量下载；只需要某条视频时，使用单条视频链接更容易确认目标。再次提交主页前核对已下载内容，避免重复。" }],
		faq: [
			{ question: "加载主页列表就会开始下载吗？", answer: "不会。需要选中资源，核对画质和数量，再点击 Add to queue。" },
			{ question: "主页上的所有作品都会出现在列表里吗？", answer: "不保证。以实际加载的资源为准，不把列表视为全部历史内容或受限内容的完整备份。" },
			{ question: "为什么有些条目只显示 Resource？", answer: "这是本例列表返回的显示名称。可以结合缩略图、媒体类型和日期核对，下载后再预览确认，不能仅凭通用标题判断内容。" },
		],
		related: ["download-douyin-video-iphone", "batch-download-tiktok-profile-iphone", "batch-download-instagram-profile-iphone"],
	},
	{
		slug: "batch-download-weibo-profile-iphone", category: "batch",
		screenshotsReady: true,
		title: "如何在 iPhone 和 iPad 上批量下载微博主页视频？",
		description: "复制微博作者主页链接，在 ClipDock影随存加载作品列表、选择视频、按需加载下一页并加入下载队列，附五张操作截图。",
		intro: "需要保存同一个微博作者的多条视频时，可以从主页链接开始批量加载作品，再挑选需要的资源下载。本文通过五张截图说明复制主页链接、加载列表、分页选择和查看下载进度的操作。",
		steps: [
			{ title: "复制微博作者主页链接", text: "在微博打开目标作者主页，点击右上角省略号展开 Share（分享）面板。在底部功能区找到链条图标的复制链接入口，截图中位于 Home 左侧，英文标签显示为 Copy…e URL。复制的是当前作者主页链接。", image: "weibo-batch-profile-orange" },
			{ title: "在 Batch 中粘贴主页地址", text: "打开 ClipDock影随存，进入底部 Extract（提取）页面，切换顶部 Batch（批量）分页。点击 Paste（粘贴），核对主页地址。本例为 weibo.com/u/1749964961；操作时使用你要下载的作者主页链接。", image: "weibo-batch-input-orange" },
			{ title: "加载列表并等待返回", text: "点击 Load list（加载列表），页面出现 Loading list（正在加载列表）时等待返回。加载列表不会直接开始下载，之后还需要选择资源并点击 Add to queue（加入队列）。", image: "weibo-batch-loading-orange" },
			{ title: "选择视频，按需加载下一页", text: "列表返回后先核对作者名称。本例显示 1 pages、16 posts、16 items，已选中 16 项。截图滚动到了第 11–16 项，列表末尾提供 Load next page（加载下一页）入口。", image: "weibo-batch-select-orange", sections: [
				{ title: "Load next page：继续查看更多作品", text: "如果已加载列表中没有需要的作品，可以点击 Load next page，等待更多条目返回后再检查选择数量。截图只展示了第一页及下一页入口，不代表已经加载作者的全部历史作品。" },
				{ title: "筛选与勾选需要的资源", text: "All 显示全部类型，Video 筛选视频，Image 筛选图片。条目右侧蓝色勾选表示已选中；Select loaded 用于选择已加载条目。只需要部分视频时调整勾选，再核对底部按钮中的数量。" },
				{ title: "批量画质与加入队列", text: "本例 Batch quality 显示 Follow download settings（跟随下载设置）。需要调整时点击该入口查看可用选项，确认画质和范围后点击 Add to queue (16)。括号里的数字是本次选择数量，实际以你的界面为准。" },
				{ title: "帖子数、资源数与使用限制", text: "posts 表示帖子数，items 表示资源数，本例恰好都是 16。其他主页可能不同；Unlimited 也是截图时的账号状态，不应理解为所有账号均无限制。更换作者可点击 Change link。" },
			] },
			{ title: "在 Manager 查看下载队列", text: "进入 Manager（管理）检查任务状态。本图显示 Active 13、Done 49、Failed 1，列表中有 Queued（排队中）条目，也有正在下载的视频及进度、速度和剩余时间。这些数字是管理器当前统计，不能直接作为本批 16 项的完成结果。", image: "weibo-batch-queue-orange", sections: [
				{ title: "完成后预览并保存", text: "等待任务完成后，到 Done（已完成）列表打开文件，检查画面和声音；需要保存到相册时再执行 Save to Photos。本组截图展示的是下载队列，未展示全部下载完成或保存成功。" },
				{ title: "检查失败条目", text: "如果有失败任务，进入 Failed 查看对应条目与错误信息，再核对链接和网络。本图没有展开失败详情，无法确定 Failed 1 的原因或是否属于本批次。" },
			] },
		],
		tips: [{ title: "分批核对下载范围", text: "先选择需要的作品，再按需加载下一页。重新提交主页前核对已下载内容，避免重复下载。列表以实际返回资源为准，不等于全部历史内容的完整备份。" }],
		faq: [
			{ question: "为什么列表只有 16 项？", answer: "本例当前加载了一页、16 项资源，底部还有 Load next page。可以继续加载并检查返回结果，实际数量取决于来源与当前加载范围。" },
			{ question: "点击加载下一页就会下载吗？", answer: "加载列表与下载是两个阶段。确认已选条目后，需要点击 Add to queue 才会加入下载队列。" },
			{ question: "可以只下载部分视频吗？", answer: "可以按需调整条目勾选状态。使用 Video 筛选后，也应核对总选择数和 Add to queue 的数量再提交。" },
		],
		related: ["batch-download-douyin-profile-iphone", "batch-download-tiktok-profile-iphone", "batch-download-instagram-profile-iphone"],
	},
	{
		slug: "batch-download-bilibili-profile-iphone", category: "batch",
		screenshotsReady: true,
		title: "如何在 iPhone 和 iPad 上批量下载 Bilibili（B 站）UP 主视频？",
		description: "复制 B 站 UP 主主页分享链接，在 ClipDock影随存加载投稿列表、选择视频、按需加载下一页并加入下载队列，附五张操作截图。",
		intro: "需要保存同一个 B 站 UP 主的多条投稿视频时，可以从个人主页的分享链接开始，在 ClipDock影随存中加载列表后选择下载。本文用五张截图说明主页短链接、分页选择、批量画质和队列管理。",
		steps: [
			{ title: "复制 UP 主主页分享链接", text: "在 Bilibili 打开目标 UP 主的个人主页，点击右上角省略号展开分享面板，再点击“复制链接”。截图中该入口位于“微博”和“更多”之间。这里分享的是 UP 主主页，复制前先确认所在页面。", image: "bilibili-batch-profile-orange" },
			{ title: "在 Batch 中粘贴主页短链接", text: "打开 ClipDock影随存，进入底部 Extract（提取）页面，切换顶部 Batch（批量）分页，点击 Paste（粘贴）。本例粘贴的是 b23.tv 开头的主页分享短链接，后续成功加载了对应 UP 主的列表。", image: "bilibili-batch-input-orange", sections: [
				{ title: "短链接也要核对来源", text: "本例直接使用复制得到的短链接，无需手动改写地址。但仅凭 b23.tv 域名无法区分主页与单条视频，应该从 UP 主主页复制，并在加载后核对作者名称。" },
			] },
			{ title: "加载投稿列表", text: "点击 Load list（加载列表），等待 Loading list（正在加载列表）提示结束。加载只获取可选择的资源，不会立即开始下载；还需要在列表中确认条目并加入队列。", image: "bilibili-batch-loading-orange" },
			{ title: "选择视频并按需加载下一页", text: "本例返回 Getfitbyivana 的列表，显示 1 pages、20 posts、20 items，已选中 20 项。截图滚动到第 15–20 项，每条视频下方有媒体类型、时长和日期，可用于核对作品。", image: "bilibili-batch-select-orange", sections: [
				{ title: "Load next page：查看更多投稿", text: "列表末尾的 Load next page（加载下一页）用于继续加载更多条目。需要更多作品时点击并等待返回，再核对新增内容和选择数量。当前 20 项是已加载范围，不代表 UP 主全部历史投稿。" },
				{ title: "筛选和勾选下载范围", text: "All 查看全部类型，Video 筛选视频，Image 筛选图片。右侧蓝色勾选表示已选中，可以按需调整；Select loaded 用于选择已加载条目。提交前检查总选择数，避免下载不需要的资源。" },
				{ title: "Batch quality：批量画质", text: "本例显示 Follow download settings（跟随下载设置）。需要调整时点击 Batch quality 查看可用选项，确认后点击 Add to queue (20)（加入队列）。截图没有展开具体清晰度菜单，可用画质以实际结果为准。" },
				{ title: "核对账号与数量", text: "Change link 可用于更换链接。posts 与 items 分别是帖子数和资源数，本例均为 20；Unlimited 是截图时的界面状态，实际使用限制以当前账号显示为准。" },
			] },
			{ title: "查看下载队列与完成结果", text: "加入队列后进入 Manager（管理）。本图显示 Active 20、Done 62、Failed 1，条目包含 Queued（排队中）以及下载进度、大小、速度和预计剩余时间。这些是管理器当前统计，不能将 Done 62 当成本批 20 项的完成数量。", image: "bilibili-batch-queue-orange", sections: [
				{ title: "长视频先确认下载范围", text: "列表中包含较长的视频，队列中也显示不同的文件大小。可先选少量需要的作品，结合实际进度安排等待时间，避免一次加入过多不需要的任务。" },
				{ title: "完成后预览与保存", text: "到 Done（已完成）列表打开已完成的视频，检查画面和声音；需要保存到相册时再执行 Save to Photos。若有失败任务，进入 Failed 查看具体错误。本组截图展示的是队列运行状态，未展示全部任务完成或保存成功。" },
			] },
		],
		tips: [{ title: "按实际列表选择作品", text: "主页批量加载范围以返回结果为准，不把它视为全部历史投稿或受限内容的完整备份。重复提交前先核对已下载内容。" }],
		faq: [
			{ question: "可以直接粘贴 b23.tv 短链接吗？", answer: "本例使用从 UP 主主页复制的 b23.tv 短链接，并加载了作品列表。应核对链接来自主页，以及返回的作者是否正确。" },
			{ question: "为什么只有 20 项资源？", answer: "本例当前只加载了一页，列表底部提供 Load next page，可以继续加载并查看实际返回的资源。" },
			{ question: "这篇也演示了合集、收藏夹或多 P 视频吗？", answer: "没有，本组截图展示的是 UP 主主页投稿列表，其他链接类型需要按各自实际流程核对。" },
			{ question: "一定能下载最高画质吗？", answer: "不能仅凭本组截图判断。图中批量画质跟随下载设置，可用清晰度以资源实际返回结果为准。" },
		],
		related: ["download-bilibili-video-iphone", "batch-download-weibo-profile-iphone", "download-youtube-playlist-iphone"],
	},
	{
		slug: "extract-audio-iphone", category: "tools",
		screenshotsReady: true,
		title: "如何在 iPhone 和 iPad 上提取视频音频？",
		description: "使用 ClipDock影随存从 iPhone 相册视频中提取 M4A 音频，查看处理结果并打开文件分享入口，附四张真实操作截图。",
		intro: "想单独保存视频里的声音？打开 ClipDock影随存的 Extract Audio（提取音频），从相册选中视频，即可生成独立的音频文件。下面用四张真实操作截图说明完整步骤。截图来自 iPhone 17 Pro Max 模拟器（iOS 26.0），App 使用英文界面，按钮附有中文对照；iPad 用户可对照相同功能入口操作。",
		steps: [
			{ title: "打开提取音频工具", text: "打开 ClipDock影随存，点击底部 Process（处理）分页，在工具列表中找到 Extract Audio（提取音频）。截图中的入口位于最下排左侧。操作前，准备好一段有声音的视频，例如自己的讲解、访谈或已获授权的素材。", image: "audio-process" },
			{ title: "从相册选择视频", text: "在 Select Video（选择视频）页面点击 Choose from Photos（从相册选择），再在系统照片选择器中点选要处理的视频。即使页面显示没有已下载视频，也不影响从相册导入。如果素材保存在“文件”App，可使用页面上的 Choose from Files（从文件选择）入口。", image: "audio-source" },
			{ title: "等待音频提取完成", text: "选中视频后，App 会直接开始提取，无需再点击开始按钮。本次操作没有出现格式设置页，完成后弹出 Processing Complete（处理完成），生成的文件名以 .m4a 结尾。点击 Share File（分享文件）继续导出；Done（完成）用于关闭提示。", image: "audio-result" },
			{ title: "打开分享与保存入口", text: "点击 Share File 后，分享面板会显示音频文件及其大小，截图中本次输出约为 2.4 MB。需要单独保存时，使用下方的保存到“文件”入口；需要交给其他 App 时，可查看“更多”中的可用选项。保存后建议打开音频试听，确认声音和时长符合预期。", image: "audio-share" },
		],
		tips: [{ title: "提取后没有声音怎么办？", text: "先播放原视频，并确认播放器没有静音。原文件没有音轨时，提取工具无法恢复不存在的声音；提取也不会自动改善原始音质。" }, { title: "下载列表为空，仍然可以继续", text: "No downloaded videos available for processing 只表示 App 中没有可供处理的已下载视频。本文使用上方的 Choose from Photos，从系统相册直接选择素材。" }],
		faq: [{ question: "可以选择 MP3 等其他格式吗？", answer: "本次实测中，选中视频后直接生成 M4A，没有出现格式选择界面。本文按这一实际流程演示，不包含 MP3 转换步骤。" }, { question: "为什么照片 App 里找不到输出？", answer: "提取结果是音频文件，不是视频或照片。请从 Share File 打开分享面板，使用保存到“文件”等入口管理音频。" }, { question: "能直接从视频分享链接提取声音吗？", answer: "本文演示的是处理相册里的已有视频。如果只有分享链接，可以先按对应平台教程保存视频，再进行音频提取。" }],
		related: ["download-youtube-video-iphone", "join-videos-iphone", "video-to-live-photo-iphone"],
	},
	{
		slug: "join-videos-iphone", category: "tools",
		screenshotsReady: true,
		title: "如何在 iPhone 和 iPad 上拼接多个视频？",
		description: "使用 ClipDock影随存拼接相册视频，了解主视频、追加片段数量、上下箭头排序、处理进度和结果保存，附六张真实操作截图。",
		intro: "把旅行片段、活动记录或分段拍摄的讲解按顺序接起来，可以使用 ClipDock影随存的 Stitch Videos（拼接视频）。本文用三个相册视频演示从导入、排序到保存的完整流程，并逐项解释设置页。截图来自 iPhone 17 Pro Max 模拟器（iOS 26.0），英文按钮附中文对照；iPad 用户可对照相同功能入口操作。",
		steps: [
			{ title: "在 Process 页面打开拼接工具", text: "打开 ClipDock影随存，点击底部 Process（处理）分页。在工具总览中，找到第二排中间的 Stitch Videos（拼接视频），点击进入。截图中的橙色箭头和边框标出了这个入口。", image: "join-process" },
			{ title: "选择主视频，读懂预览信息", text: "进入 Select Video（选择视频）后，通过 Choose from Photos（从相册选择）选中第一段视频。这段是主视频，会作为拼接结果的开头。进入截图中的设置页后，先核对素材。", image: "join-settings", sections: [
				{ title: "预览、文件名与时间轴", text: "点击画面中央的播放按钮预览主视频。下方显示文件名、播放位置和主视频时长，便于确认选对了版本。本例主视频时长为 02:26；这里显示的还不是拼接后总时长。" },
				{ title: "640×338 是什么？", text: "这是当前主视频的画面尺寸，单位为像素。它是素材信息，不是输出尺寸选择器。本次拼接设置页没有独立的分辨率、帧率或画质选项。" },
				{ title: "为什么已经选了视频，却显示 0 clips added？", text: "这个数字只统计通过 Add Video 追加的片段，不包含上方主视频。0 表示还没有追加片段；要拼接多个视频，下一步至少再添加一段。" },
			] },
			{ title: "添加后续视频片段", text: "点击 Processing Options（处理选项）下的 Add Video（添加视频），在 Select Videos to Stitch 弹窗里选择素材来源。本例继续选择 Choose from Photos。", image: "join-source", sections: [
				{ title: "三个来源如何选择", text: "Choose from Downloads 对应 App 中已下载的视频；Choose from Photos 对应系统相册；Choose from Files 用于从文件选择器导入。按素材所在位置选择即可，不需要为了拼接先重新下载相册视频。" },
				{ title: "在相册中多选并确认", text: "点选要追加的视频后，缩略图上会出现选中编号，再点击右上角的蓝色勾号完成导入。需要更多片段时，可以再次点击 Add Video。返回后检查列表数量，避免把主视频重复添加一次。" },
			] },
			{ title: "核对数量，调整播放顺序", text: "截图中显示 2 clips added，表示在主视频后追加了两段，最终共三段。列表从 Clip 2 开始编号，按从上到下的顺序接在主视频之后。", image: "join-order", sections: [
				{ title: "上下箭头：调整追加片段顺序", text: "点击向上或向下箭头移动对应片段。本次已实测把 05:11 的片段移到 04:10 的片段前面。最上面的追加片段不能继续上移，最下面的不能继续下移，因此边界处的箭头会变灰；只有一段追加视频时，两个方向都不可用。" },
				{ title: "主视频与追加列表的区别", text: "上方主视频固定作为开头，不在追加片段的排序列表里。如果想换一个视频开场，返回重新选择主视频，再添加后续片段。" },
				{ title: "缩略图、时长与移除按钮", text: "每行的缩略图、文件名和时长帮助你区分片段；红色垃圾桶是该追加片段的移除入口。开始前核对顺序、重复素材和总内容。本例顺序为主视频 02:26 → Clip 2 05:11 → Clip 3 04:10。" },
			] },
			{ title: "开始拼接，查看处理进度", text: "确认片段后点击 Start Processing（开始处理）。进度弹窗会显示 Processing video 和完成百分比，等待结果页出现后再检查成片。", image: "join-progress", sections: [
				{ title: "完成通知与后台提示", text: "较长的处理过程中会出现 Notify me when complete（完成时通知我）开关。需要提醒时可以开启，并按系统提示处理通知权限。弹窗提示可以切到后台，App 会尽可能继续处理；这不代表系统一定允许任务一直在后台运行。" },
				{ title: "Cancel 是取消处理", text: "弹窗底部 Cancel 用于取消当前任务，不是把进度窗口收起。仍然需要这次输出时，保持任务运行并等待完成。" },
			] },
			{ title: "预览成片并保存到相册", text: "完成后结果页会显示生成的视频、时间轴和缩略图。本次输出文件以 _concat.mp4 结尾，结果页显示 11:46，已验证能够播放。输入列表的时长按秒显示，核对总时长时应以实际输出为准。", image: "join-result", sections: [
				{ title: "保存前检查哪些地方", text: "点击播放按钮预览，重点查看开头、结尾与两段连接附近，确认顺序、画面比例和声音衔接。对本例可重点检查约 02:26 和 07:37 附近；完整观看或试听后再决定是否保留成片。" },
				{ title: "Save to Photos：保存到相册", text: "点击 Save to Photos（保存到相册）。首次使用可能需要允许 App 添加照片和视频；保存完成后会出现 Saved to Photos 提示。本次实测已收到这一成功提示，可以再到照片 App 查看成片。" },
				{ title: "继续处理、分享与完成", text: "Keep Processing 是继续处理入口；Share File 打开文件分享；Done 关闭结果页。需要把成片留在相册时，应先点击 Save to Photos，不能把 Done 当作保存按钮。" },
			] },
		],
		tips: [{ title: "横竖屏或尺寸不一致怎么办？", text: "本次拼接页没有单独的画布、裁切或留边设置。对画面比例有要求时，先用 Resize / Canvas（调整尺寸／画布）或相应工具准备素材，再进行拼接，并检查输出效果。" }, { title: "暂时不要离开当前设置页", text: "右上角魔棒会将当前主视频带入 Quick Edit（快速编辑）工具选择。本次实测从那里重新进入 Stitch Videos 后，追加数量重置为 0。如果已排好顺序，直接开始处理；切换工具后应重新核对追加列表。" }],
		faq: [{ question: "为什么 2 clips added 却拼出了三段？", answer: "计数只包含追加视频，不包含开头的主视频。主视频一段加追加两段，共三段。" }, { question: "可以把追加片段移到主视频前面吗？", answer: "本次界面的上下箭头只调整追加列表内部顺序，第一段追加视频的向上箭头为灰色。需要更换开头时，应重新选择主视频。" }, { question: "这里能设置转场、背景音乐或输出画质吗？", answer: "本次拼接设置页没有这些选项。页面主要用于预览主视频、添加片段及调整追加顺序；需要其他效果时，使用对应处理工具。" }, { question: "点击 Done 后为什么相册里没有成片？", answer: "Done 只关闭结果页。需要另行点击 Save to Photos，并确认保存成功及相册权限。" }],
		related: ["extract-audio-iphone", "video-to-live-photo-iphone", "download-youtube-playlist-iphone"],
	},
	...videoToolTutorials,
];

// Keep tool cards in the same order as the app’s Process grid.
const orderedTools = tutorials.filter(article => article.category === "tools").sort((a, b) => videoToolOrder.indexOf(a.slug) - videoToolOrder.indexOf(b.slug));
let toolIndex = 0;
for (let index = 0; index < tutorials.length; index++) {
	if (tutorials[index].category === "tools") tutorials[index] = orderedTools[toolIndex++];
}

export const articleHref = (slug: string) => `/zh-Hans/articles/${slug}/`;
